//! Real-install verification for `Settings::use_imported_pairs` (on by
//! default): classifies every imported pair
//! rule against the derived edges the analyzer already produces between
//! the same two mods, writes the novel (unreconstructable) ones to
//! `.journal/local/novel-pair-rules.md` for review, and re-baselines the
//! sorter with imported pairs enforced against a sort without them.
//!
//! `#[ignore]`d: reads `.journal/local/report.json` (skips gracefully when
//! absent — regenerate it with the analyzer's `analyze --json`) and the
//! real RimSort database directory, read-only
//! (`%LOCALAPPDATA%\RimSort\dbs` by default, overridable via
//! `RIMMERGE_RIMSORT_DIR` — skips gracefully when it isn't there either).
//! Needs `RIMMERGE_PERF_PROFILE_DIR` for the importer's own
//! snapshot-copy write (never the real profile) — the same requirement
//! every other real-install test in this crate has (see the root
//! `CLAUDE.md`); unset, this early-returns with a `skipping:` line rather
//! than asserting nothing silently.
//!
//! Run with:
//! `RIMMERGE_GAME_DIR=<your install> RIMMERGE_PERF_PROFILE_DIR=<scratch dir> cargo nextest run -p rimmerge-cli --all-features --release --run-ignored ignored-only -E 'binary(real_install_pair_rules)'`

mod common;

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::time::Instant;

use rim_analyzer::domain::{EdgeKind, LoadOrder, ModId, Report};
use rim_resolve::domain::{
    PairRule, PairRuleEvidence, Rule, RuleSet, SorterOverrides, Tagging, classify_pair_rule,
};
use rim_resolve::sort::{EnforcedLayers, Layer, SortInput, TieBreak, sort};
use rim_session::ports::{RimSortImporter as RimSortImporterPort, RimSortPaths};

fn load_report(path: &Path) -> Option<Report> {
    let bytes = std::fs::read(path).ok()?;
    match serde_json::from_slice(&bytes) {
        Ok(report) => Some(report),
        Err(error) => panic!("failed to parse {}: {error}", path.display()),
    }
}

/// RimSort's own default database directory, overridable for a machine
/// that keeps it elsewhere — never a hardcoded assumption about where
/// this reader's own install lives.
fn rimsort_dbs_dir() -> Option<PathBuf> {
    if let Ok(dir) = std::env::var("RIMMERGE_RIMSORT_DIR") {
        return Some(PathBuf::from(dir));
    }
    std::env::var("LOCALAPPDATA")
        .ok()
        .map(|local| PathBuf::from(local).join("RimSort").join("dbs"))
}

fn rimsort_paths(dir: &Path) -> RimSortPaths {
    RimSortPaths {
        user_rules: Some(dir.join("userRules.json")),
        community_rules: Some(
            dir.join("Community-Rules-Database")
                .join("communityRules.json"),
        ),
        steam_db: Some(dir.join("Steam-Workshop-Database").join("steamDB.json")),
    }
}

fn pair_rules(rules: &[Rule]) -> Vec<&PairRule> {
    rules
        .iter()
        .filter_map(|rule| match rule {
            Rule::Pair(pair) => Some(pair),
            Rule::Placement(_) | Rule::Incompatible(_) => None,
        })
        .collect()
}

/// The markdown artifact this test writes for review: every imported pair
/// rule with no derived edge in either direction — the "genuine community
/// knowledge" `use_imported_pairs=true` newly enforces. Sorted by mod id
/// pair for a stable, reviewable diff across re-runs.
fn render_novel_pairs_markdown(report: &Report, novel: &[&PairRule]) -> String {
    let mut sorted: Vec<&&PairRule> = novel.iter().collect();
    sorted.sort_by(|a, b| (&a.after, &a.before).cmp(&(&b.after, &b.before)));

    let mut out = String::new();
    let _ = writeln!(out, "# Novel imported pair rules\n");
    let _ = writeln!(
        out,
        "Generated by `apps/cli/tests/real_install_pair_rules.rs` against \
         `.journal/local/report.json` ({} mods) and the real RimSort database directory. \
         Every row below is an imported pair rule with **no** derived edge \
         connecting the same two mods in either direction — the community \
         knowledge `use_imported_pairs=true` newly enforces that no About.xml/\
         DLL fact in this install already states. See this file's own eprintln \
         output for the redundant/contradicting counts this list excludes.\n",
        report.mods.len()
    );
    let _ = writeln!(out, "{} novel rules.\n", sorted.len());
    let _ = writeln!(out, "| after | before | origin | comment |");
    let _ = writeln!(out, "|---|---|---|---|");
    for rule in sorted {
        let _ = writeln!(
            out,
            "| {} | {} | {:?} | {} |",
            rule.after,
            rule.before,
            rule.origin,
            rule.comment.as_deref().unwrap_or("-")
        );
    }
    out
}

/// This file's own "Run with" invocation (this module's own doc comment,
/// above) — named in [`common::require_profile_dir`]'s panic message.
const RERUN_COMMAND: &str = "RIMMERGE_GAME_DIR=<your install> RIMMERGE_PERF_PROFILE_DIR=<scratch dir> cargo nextest run -p \
     rimmerge-cli --all-features --release --run-ignored ignored-only -E \
     'binary(real_install_pair_rules)'";

/// One toggle combination's own sort, for the before/after re-baseline —
/// the default tie-break (`Rebuild`) throughout, since the imported-pairs
/// toggle is the only thing under test here.
fn sort_with_pairs_toggle(
    report: &Report,
    raw_rules: &RuleSet,
    use_imported_pairs: bool,
) -> rim_resolve::sort::SortOutcome {
    let rules = rim_session::filter_imported_rules(raw_rules.clone(), use_imported_pairs, true);
    let current = LoadOrder::new(report.mods.iter().map(|m| m.id.clone()).collect());
    sort(&SortInput {
        report,
        rules: &rules,
        tagging: &Tagging::default(),
        overrides: &SorterOverrides::default(),
        current: &current,
        enforce: EnforcedLayers::default(),
        tie_break: TieBreak::Rebuild,
    })
}

#[test]
#[ignore = "reads .journal/local/report.json and the real RimSort database dir; needs RIMMERGE_PERF_PROFILE_DIR"]
fn imported_pair_rule_classification_rebaseline_and_cycle_check() {
    let report_path =
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../.journal/local/report.json");
    let Some(report) = load_report(&report_path) else {
        eprintln!("skipping: {} not found", report_path.display());
        return;
    };

    let Some(scratch) = common::require_profile_dir(RERUN_COMMAND) else {
        return;
    };

    let Some(dbs_dir) = rimsort_dbs_dir() else {
        eprintln!("skipping: neither RIMMERGE_RIMSORT_DIR nor LOCALAPPDATA is set");
        return;
    };
    let paths = rimsort_paths(&dbs_dir);
    if !paths.user_rules.as_deref().is_some_and(Path::is_file) {
        eprintln!(
            "skipping: no real RimSort database directory at {} (userRules.json not found)",
            dbs_dir.display()
        );
        return;
    }

    let start = Instant::now();

    let active: BTreeMap<ModId, Option<u64>> = report
        .mods
        .iter()
        .map(|m| (m.id.clone(), m.workshop_id))
        .collect();

    let importer = rim_io::RimSortImporter::new(scratch);
    let imported = importer
        .import(&paths, &active)
        .expect("importing the real RimSort databases must succeed");

    // Every path this test passes is `Some` (built by `rimsort_paths`
    // above, all three joined from the same real `dbs_dir`), so every
    // field of `imported` is `Some` too — `unwrap_or_default` here is
    // just the un-wrapping step, never a "source wasn't imported" case
    // this test needs to handle.
    let user_rules = imported.user_rules.unwrap_or_default();
    let community_rules = imported.community_rules.unwrap_or_default();
    let steam_dependencies = imported.steam_dependencies.unwrap_or_default();

    let mut all_rules: Vec<Rule> = Vec::new();
    all_rules.extend(user_rules.iter().cloned());
    all_rules.extend(community_rules.iter().cloned());
    all_rules.extend(steam_dependencies.iter().cloned());
    let raw_rule_set = RuleSet::new(all_rules.clone());

    // -- Classification (requirement 1/4: redundant/novel/contradicting) --

    eprintln!(
        "raw import: user_rules={} community_rules={} steam_dependencies={}",
        user_rules.len(),
        community_rules.len(),
        steam_dependencies.len()
    );
    eprintln!(
        "raw pair counts by origin: user={} community={} steam={}",
        pair_rules(&user_rules).len(),
        pair_rules(&community_rules).len(),
        pair_rules(&steam_dependencies).len()
    );

    let pairs = pair_rules(&all_rules);
    let mut redundant_by_kind: BTreeMap<EdgeKind, usize> = BTreeMap::new();
    let mut redundant = 0usize;
    let mut novel: Vec<&PairRule> = Vec::new();
    let mut contradicting: Vec<(&PairRule, std::collections::BTreeSet<EdgeKind>)> = Vec::new();

    for rule in &pairs {
        match classify_pair_rule(rule, &report) {
            PairRuleEvidence::Redundant(kinds) => {
                redundant += 1;
                for kind in kinds {
                    *redundant_by_kind.entry(kind).or_default() += 1;
                }
            }
            PairRuleEvidence::Contradicting(kinds) => contradicting.push((rule, kinds)),
            PairRuleEvidence::Novel => novel.push(rule),
        }
    }

    eprintln!(
        "imported pairs: {} total, {} redundant ({:.0}%), {} novel, {} contradicting",
        pairs.len(),
        redundant,
        100.0 * redundant as f64 / pairs.len().max(1) as f64,
        novel.len(),
        contradicting.len()
    );
    eprintln!("redundant by covering edge kind: {redundant_by_kind:?}");
    for (rule, kinds) in &contradicting {
        eprintln!(
            "contradiction: {} after {} (origin {:?}) opposed by {:?}",
            rule.after, rule.before, rule.origin, kinds
        );
    }
    assert_eq!(
        redundant + novel.len() + contradicting.len(),
        pairs.len(),
        "every pair rule must fall into exactly one category"
    );
    // The redundant/novel split is a property of *this install's* own
    // imported rule set against its own derived edges, not a structural
    // fact any install must satisfy — a different mod set could
    // genuinely redistribute it. Named only through
    // `RIMMERGE_EXPECTED_PAIR_RULE_SPLIT=<min redundant %>,<max novel %>`;
    // unset, this prints the measured split without asserting one.
    let redundant_pct = 100 * redundant / pairs.len().max(1);
    let novel_pct = 100 * novel.len() / pairs.len().max(1);
    match std::env::var("RIMMERGE_EXPECTED_PAIR_RULE_SPLIT") {
        Ok(raw) => {
            let (min_redundant_str, max_novel_str) = raw.split_once(',').unwrap_or_else(|| {
                panic!(
                    "RIMMERGE_EXPECTED_PAIR_RULE_SPLIT must be '<min redundant %>,<max novel %>', got {raw}"
                )
            });
            let min_redundant_pct: usize = min_redundant_str.parse().unwrap_or_else(|_| {
                panic!(
                    "RIMMERGE_EXPECTED_PAIR_RULE_SPLIT's redundant-% field must be a number, got {min_redundant_str}"
                )
            });
            let max_novel_pct: usize = max_novel_str.parse().unwrap_or_else(|_| {
                panic!(
                    "RIMMERGE_EXPECTED_PAIR_RULE_SPLIT's novel-% field must be a number, got {max_novel_str}"
                )
            });
            assert!(
                redundant_pct >= min_redundant_pct,
                "expected at least {min_redundant_pct}% of imported pairs to be redundant with a \
                 derived edge, got {redundant}/{} ({redundant_pct}%)",
                pairs.len()
            );
            assert!(
                novel_pct <= max_novel_pct,
                "expected at most {max_novel_pct}% of imported pairs to be novel, got {}/{} ({novel_pct}%)",
                novel.len(),
                pairs.len()
            );
        }
        Err(_) => {
            eprintln!(
                "RIMMERGE_EXPECTED_PAIR_RULE_SPLIT not set -- measured split: {redundant_pct}% \
                 redundant, {novel_pct}% novel (not asserted)"
            );
        }
    }
    // Zero contradictions is the expected state. A vanilla child def
    // inheriting a template name that vanilla itself registers resolves
    // against that vanilla registration
    // (`Verse.XmlInheritance.GetBestParentFor`, `loadOrder <=` its own,
    // trivially), so no ordering fact — and no `ParentTemplate` edge —
    // exists between a DLC and a content mod that happens to register the
    // same template name. Imported rules on such pairs are simply
    // `Novel`/`Redundant` like the rest. On a real install most imported
    // pairs are redundant with a derived edge (`ParentTemplate` among the
    // edge kinds covering them) and the remainder are novel.
    //
    // If this ever fires, read the opposing edge's own
    // `EdgeStrength` first: an `Awareness` or `Inferred` one is the
    // harmless kind this classification exists for (`RetextureAfterOwner`
    // edges are *expected* to contradict an
    // imported rule on a retexture pack, and an imported rule outranks
    // `Layer::Inferred` by construction), while a `Hard`/`Declared` one
    // is a real disagreement that `DeclarationQuestioned`/`RuleOverruled`
    // — not this test — is responsible for.
    assert_eq!(
        contradicting.len(),
        0,
        "expected no imported pair rule to contradict a derived edge: {contradicting:?}"
    );
    // -- Artifact: the novel-rule list, for review --

    let novel_markdown = render_novel_pairs_markdown(&report, &novel);
    let artifact_path =
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../.journal/local/novel-pair-rules.md");
    std::fs::write(&artifact_path, &novel_markdown)
        .unwrap_or_else(|error| panic!("write {}: {error}", artifact_path.display()));
    eprintln!(
        "wrote {} novel pair rules to {}",
        novel.len(),
        artifact_path.display()
    );

    // -- Re-baseline (requirement 5): before (pairs off) vs after (pairs on) --

    let before = sort_with_pairs_toggle(&report, &raw_rule_set, false);
    let after = sort_with_pairs_toggle(&report, &raw_rule_set, true);

    eprintln!(
        "kendall_tau_inversions: before(pairs=false)={} after(pairs=true)={} (+{})",
        before.stats.kendall_tau_inversions,
        after.stats.kendall_tau_inversions,
        after.stats.kendall_tau_inversions as i64 - before.stats.kendall_tau_inversions as i64
    );
    eprintln!(
        "positions_changed: before={} after={} (out of {} mods)",
        before.stats.positions_changed,
        after.stats.positions_changed,
        report.mods.len()
    );

    let tail: Vec<&str> = after
        .order
        .as_slice()
        .iter()
        .rev()
        .take(3)
        .map(ModId::as_str)
        .collect();
    eprintln!("last 3 in suggested order (pairs=true): {tail:?}");
    // Named only through this env var -- a comma-separated list of exactly
    // 3 mod ids, most-recent first (matching `tail`'s own `.rev()`). Unset,
    // this block
    // only re-prints the real tail above rather than asserting it, since
    // the exact ids are this maintainer's own subscription list, not a
    // structural fact `rim-resolve` promises.
    if let Some(expected) = common::require_pin_var(
        "RIMMERGE_EXPECTED_ORDER_TAIL",
        "RIMMERGE_GAME_DIR=<install> RIMMERGE_PERF_PROFILE_DIR=<scratch dir> \
         RIMMERGE_EXPECTED_ORDER_TAIL=<mod>,<mod>,<mod> cargo nextest run -p rimmerge-cli \
         --all-features --release --run-ignored ignored-only -E 'binary(real_install_pair_rules)'",
    ) {
        let expected: Vec<&str> = expected.split(',').collect();
        assert_eq!(
            tail, expected,
            "the motivating case: the pinned mod must land after the pinned \
             predecessors, which must land after everything else, once use_imported_pairs is on"
        );
    }

    // -- Cycle-drop check --

    eprintln!(
        "dropped edges: before(pairs=false)={} after(pairs=true)={}",
        before.dropped.len(),
        after.dropped.len()
    );
    let new_hard_drops: Vec<_> = after
        .dropped
        .iter()
        .filter(|d| d.edge.layer == Layer::Hard)
        .collect();
    assert!(
        new_hard_drops.is_empty(),
        "enabling use_imported_pairs must never cause a Hard-layer edge to be dropped to break \
         a cycle — that would be a genuine regression, not a tuning detail: {new_hard_drops:?}"
    );
    let before_hard_drops = before
        .dropped
        .iter()
        .filter(|d| d.edge.layer == Layer::Hard)
        .count();
    assert_eq!(
        before_hard_drops, 0,
        "the pre-existing (pairs=false) baseline must also have zero Hard-layer drops, or the \
         comparison above proves nothing"
    );

    eprintln!(
        "imported_pair_rule_classification_rebaseline_and_cycle_check: {:?}",
        start.elapsed()
    );
}
