//! Exporting a project, optionally installing it.

use std::path::Path;

use rim_session::use_cases::{AssignmentExportOptions, ExportAssignment};

use super::projects::parse_assignment_id;
use crate::dto::assignment::{ExportAssignmentReportDto, ExportAssignmentRequestDto};
use crate::error::CommandError;
use crate::state::{AppState, with_session};

/// Renders, writes, and (when asked) installs `request.assignment_id`'s
/// assignment project. Refuses to write to the game's `Mods` folder
/// while `RimWorldWin64.exe` looks like it's running unless
/// `request.force` is set — the same gate
/// [`crate::commands::patch::export_patch`] uses.
///
/// # Errors
///
/// Returns [`CommandError::no_project_loaded`] when no project is
/// loaded, [`CommandError::rimworld_running`] when `request.install` is
/// set, the game process is detected, and `request.force` is `false`,
/// [`CommandError::assignment_not_found`] when `request.assignment_id`
/// isn't loaded, [`CommandError::invalid_input`] when there's nothing to
/// export or `request.out_dir` is (or is inside) the game's `Mods`
/// folder or an existing folder not generated by this project, or
/// [`CommandError`] when rendering, writing, or persisting fails.
pub(crate) async fn export_assignment_inner(
    state: &AppState,
    request: ExportAssignmentRequestDto,
) -> Result<ExportAssignmentReportDto, CommandError> {
    let adapters = state.adapters.clone();
    let probe = std::sync::Arc::clone(&state.game_process_probe);
    with_session(state, move |session| {
        let id = parse_assignment_id(&request.assignment_id)?;
        if request.install && !request.force && probe.is_running() {
            return Err(CommandError::rimworld_running());
        }

        // Absolutized/canonicalized the same way `export_patch_inner`
        // does — see that command's own doc comment for why.
        let out_dir = rim_io::resolve_user_dir(Path::new(&request.out_dir)).map_err(|error| {
            CommandError::invalid_input(format!("resolving out_dir {}: {error}", request.out_dir))
        })?;

        let use_case = ExportAssignment::new(
            adapters.merge_mod_writer,
            adapters.config_store,
            adapters.assignment_store,
        );
        let outcome = use_case.execute(
            session,
            &id,
            AssignmentExportOptions {
                out_dir,
                install: request.install,
            },
        )?;

        Ok(ExportAssignmentReportDto {
            export_path: outcome.export_path.display().to_string(),
            installed_path: outcome
                .installed_path
                .map(|path| path.display().to_string()),
            mods_config_backup_path: outcome
                .mods_config_backup
                .map(|path| path.display().to_string()),
            skipped: outcome.skipped.iter().map(Into::into).collect(),
            files: outcome
                .files
                .iter()
                .map(|path| path.display().to_string())
                .collect(),
            content_sha256: outcome.content_sha256,
        })
    })
    .await
}
