//! Export options, the export outcome and its skipped items, and export errors.

use std::path::PathBuf;

use rim_merge::assign::{self};
use rim_merge::emit::{self};

use crate::UnknownAssignment;
use crate::ports::{ConfigError, MergeModError, StoreError};
use crate::use_cases::export_folder::{EnsureNotForeignError, ForeignFolderError, InstallError};

/// One field a render skipped, whether because
/// [`rim_merge::assign::render_sections`] couldn't safely render it or
/// because this use case's own validation
/// ([`validate_and_clean_sections`](crate::use_cases::export_assignment::validation::validate_and_clean_sections))
/// found a chosen item no longer active or no longer a current own
/// instance. That validation is the *only* place the dangling
/// own-reference check happens (see its own doc comment). A plain alias
/// for the engine's own unified type — `SkippedField` already names its
/// own section (`def_type`) and addresses either row shape
/// (`row: RowKey`), so there is nothing for a wrapping type here to add,
/// since this use case spans every section at once.
pub type AssignmentSkip = assign::SkippedField;

/// Where an assignment export lands, and whether it should also be
/// installed — the [`ExportPatch`](crate::use_cases::ExportPatch) shape, [`ExportOptions`](crate::use_cases::ExportOptions)'s
/// twin.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AssignmentExportOptions {
    /// The folder to render the project into — never `<game>/Mods` or a
    /// subfolder of it (see [`ExportAssignmentError::OutDirIsModsFolder`]).
    pub out_dir: PathBuf,
    /// Also copy the same rendered folder into `<game>/Mods` and activate
    /// it (append its package id to the current `ModsConfig.xml` order, if
    /// absent). The running-game refusal/`force` gate is the interface
    /// layer's own job, exactly like [`ExportOptions::install`](crate::use_cases::ExportOptions::install).
    pub install: bool,
}

/// What [`ExportAssignment::execute`](crate::use_cases::export_assignment::ExportAssignment::execute) did — [`ExportOutcome`](crate::use_cases::ExportOutcome)'s
/// twin, with `skipped` shaped for a project instead of a `FindingKey`
/// list.
#[derive(Debug, Clone, PartialEq)]
pub struct AssignmentExportOutcome {
    /// `<out_dir>/<folder_name>` — where the project was written.
    pub export_path: PathBuf,
    /// `<game>/Mods/<folder_name>`, when [`AssignmentExportOptions::install`]
    /// copied the same rendered folder there.
    pub installed_path: Option<PathBuf>,
    /// The `ModsConfig.xml` backup path, when `install` wrote it.
    pub mods_config_backup: Option<PathBuf>,
    /// Every field this export couldn't render, across every section —
    /// the export still went ahead without them. Each names its own
    /// section (`SkippedField::def_type`) and row (`SkippedField::row`).
    pub skipped: Vec<AssignmentSkip>,
    /// Every written file's path, relative to [`Self::export_path`].
    pub files: Vec<PathBuf>,
    /// The canonical hash of the project this export was built from
    /// ([`AssignmentProject::content_sha256`](rim_resolve::domain::AssignmentProject::content_sha256)).
    pub content_sha256: String,
}

/// Everything that can go wrong exporting an assignment project.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum ExportAssignmentError {
    /// No assignment project with the given id is loaded.
    #[error(transparent)]
    Unknown(#[from] UnknownAssignment),
    /// Every row was skipped (or there were none), so there is nothing to
    /// write.
    #[error("this assignment project has nothing ready to export")]
    NothingToExport,
    /// `out_dir` is, or is inside, the game's `Mods` folder — refused;
    /// [`AssignmentExportOptions::install`] is the only sanctioned way to
    /// write there.
    #[error("{0} is inside the game's Mods folder; use install instead")]
    OutDirIsModsFolder(PathBuf),
    /// `out_dir` isn't absolute.
    #[error("{0} must be an absolute path")]
    OutDirNotAbsolute(PathBuf),
    /// The target folder already exists and isn't this project's own
    /// previous export.
    #[error("{path} already exists and wasn't generated by this project", path = path.display())]
    ForeignFolder {
        /// The folder that already exists and isn't this project's own.
        path: PathBuf,
    },
    /// Writing the rendered folder failed.
    #[error(transparent)]
    Write(#[from] MergeModError),
    /// Rendering the project's own files failed.
    #[error(transparent)]
    Emit(#[from] emit::EmitError),
    /// Persisting the export target on the project failed. The files
    /// already written to disk are **not** rolled back — only the
    /// project's own `export_dir` bookkeeping is.
    #[error("saving the assignment project: {0}")]
    Store(StoreError),
    /// Writing `ModsConfig.xml` during install failed.
    #[error(transparent)]
    Config(#[from] ConfigError),
}

impl From<EnsureNotForeignError> for ExportAssignmentError {
    fn from(error: EnsureNotForeignError) -> Self {
        match error {
            EnsureNotForeignError::Foreign(ForeignFolderError { path }) => {
                Self::ForeignFolder { path }
            }
            EnsureNotForeignError::Read(error) => Self::Write(error),
        }
    }
}

impl From<InstallError> for ExportAssignmentError {
    fn from(error: InstallError) -> Self {
        match error {
            InstallError::Write(error) => Self::Write(error),
            InstallError::Config(error) => Self::Config(error),
        }
    }
}
