//! [`Mod`]: a single RimWorld mod as discovered on disk.

use std::collections::BTreeSet;
use std::path::PathBuf;

use serde::{Deserialize, Serialize};

use super::declared_order::DeclaredOrder;
use super::mod_id::ModId;
use super::source::Source;

/// A RimWorld mod as discovered on disk: identity, metadata, and the
/// declared load-order hints from its `About.xml`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Mod {
    pub id: ModId,
    pub name: String,
    pub authors: Vec<String>,
    pub url: Option<String>,
    pub path: PathBuf,
    pub source: Source,
    pub supported_versions: Vec<String>,
    pub declared: DeclaredOrder,
    /// Folders under `path` that load-folder resolution selected for this
    /// mod, in **load priority order** — `ModContentPack
    /// .foldersToLoadDescendingOrder`, highest-priority folder first
    /// (version folder, `Common`, mod root, in that priority order for the
    /// default rule; the last-listed `<li>` first for an explicit
    /// `LoadFolders.xml` block — or every folder, in `--all-folders`
    /// diagnostic mode). This is also the order `infra::mod_scan` itself
    /// walks folders in, so it decides the order of this mod's own
    /// `defs`/`templates`/`patch_ops`/`assemblies` too, not just which
    /// folder wins a same-relative-path collision.
    pub loaded_folders: Vec<PathBuf>,
    /// The Steam Workshop published-file id, parsed from the workshop
    /// content folder name (`<workshop_dir>/<id>/`). `None` for local,
    /// Core, and DLC mods, which have no such folder. `#[serde(default)]`
    /// so a report cached before this field existed still deserializes.
    #[serde(default)]
    pub workshop_id: Option<u64>,
    /// Distinct active mods with a Hard-strength edge pointing at this mod.
    pub hard_dependents: usize,
    /// Distinct active mods with a Soft-strength edge (a lazily-resolved
    /// `AssemblyRef`) pointing at this mod.
    pub soft_dependents: usize,
    /// Distinct active mods with an Awareness-strength edge pointing at
    /// this mod.
    pub awareness_dependents: usize,
    /// `true` when `hard_dependents` is large enough that this mod is
    /// likely a shared framework other mods build on.
    pub is_framework_candidate: bool,
    /// `Some` when the folder carries a `rimmerge.json` marker: this mod
    /// was generated by Rimmerge (the profile merge mod or an exported
    /// compat patch). `#[serde(default)]` so every cached report written
    /// before this field existed still deserializes.
    #[serde(default)]
    pub generated: Option<GeneratedMarker>,
    /// Whether this mod's own `LoadFolders.xml` carries an exact `<vX.Y>`
    /// block for the running game version —
    /// [`crate::extract::load_folders::has_exact_version_block`]'s own query,
    /// **not** [`crate::extract::load_folders::resolve_version_entry`]'s
    /// fallback-aware one (the two questions are different — see that
    /// function's own doc comment for why a file with `<default>` and no
    /// exact block must still read `Some(false)` here). `None` when the mod
    /// ships no `LoadFolders.xml` at all (a genuine "not found");
    /// `Some(false)` when the file exists but either couldn't be read at all
    /// (a permission error or an over-size file must not collapse into
    /// `None`, which the guard would read as "no file", i.e. unguarded) or
    /// has no exact block for the running version (or failed to parse —
    /// folded into `Some(false)` too, conservatively); `Some(true)` only when
    /// the exact block genuinely exists.
    ///
    /// A `Some(false)` mod's folders are resolved via RimWorld's real
    /// descending-version-then-`<default>` fallback, implemented in
    /// [`crate::extract::load_folders::resolve_version_entry`]'s own
    /// selection logic; this field never models that fallback, it only
    /// answers "does the *exact* `<vX.Y>` block for this game version exist".
    /// The fallback is usually correct, so `rim-session`'s
    /// `ContributesNothing` guard that consumes this field is
    /// over-conservative rather than load-bearing.
    ///
    /// `#[serde(default)]` so a report cached before this field existed still
    /// deserializes, reading back `None` — the same value a mod with no
    /// `LoadFolders.xml` gets, which is a misreport for an under-scanned one.
    /// **This is a disclosed, structural gap, not an enforced one**: no code
    /// path in this workspace ever deserializes a cached `Report` back into a
    /// live `Session` (every real session comes from `AnalyzerScanner`, which
    /// always re-scans), so the hazard is latent — but nothing here rejects a
    /// stale report on `schema_version` grounds, and a caller that ever gains
    /// such a path must not trust `load_folders_version_matched` on a report
    /// predating [`super::REPORT_SCHEMA_VERSION`] 7 without checking that
    /// itself.
    #[serde(default)]
    pub load_folders_version_matched: Option<bool>,
}

/// What kind of Rimmerge-generated mod a [`GeneratedMarker`] describes.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum GeneratedKind {
    /// The per-profile merge mod (`rimmerge.merge.<hash>`).
    Merge,
    /// An exported compatibility patch, scoped to two or more mods.
    Patch,
    /// An exported assignment project (the patch maker): one new `Defs/`
    /// instance per target def, scoped to its reference set **R** plus its
    /// target set **T**.
    Assignment,
}

/// The parsed contents of a mod folder's `rimmerge.json` marker —
/// RimWorld ignores the file, but its presence means this folder was
/// generated by Rimmerge rather than authored by hand.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct GeneratedMarker {
    pub kind: GeneratedKind,
    /// The compat patch's id, when `kind` is [`GeneratedKind::Patch`]; the
    /// assignment project's id, when `kind` is [`GeneratedKind::Assignment`]
    /// — the same slot, reused rather than duplicated, since a mod is never
    /// both at once. On the wire (`extract::rimmerge_marker`) an assignment
    /// marker names this `assignmentId`, not `patchId`.
    pub patch_id: Option<String>,
    /// The mods this generated mod declares itself *about* (`rimmerge.json`'s
    /// `scope`); `None` = unrestricted (the profile merge mod).
    pub scope: Option<BTreeSet<ModId>>,
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A `Mod` serialized before `generated` existed (no such key at all)
    /// must still deserialize — the contract `#[serde(default)]` exists to
    /// guarantee: an older cached `report.json` is not a hard break.
    #[test]
    fn a_mod_json_from_before_the_generated_field_existed_still_deserializes() {
        let json = r#"{
            "id": "sample.mod",
            "name": "Sample Mod",
            "authors": [],
            "url": null,
            "path": "SampleMod",
            "source": "local",
            "supported_versions": [],
            "declared": {
                "load_after": [], "load_before": [], "force_load_after": [],
                "force_load_before": [], "dependencies": [], "incompatible_with": []
            },
            "loaded_folders": [],
            "hard_dependents": 0,
            "soft_dependents": 0,
            "awareness_dependents": 0,
            "is_framework_candidate": false
        }"#;

        let mod_entry: Mod =
            serde_json::from_str(json).expect("must deserialize without `generated`");

        assert_eq!(mod_entry.generated, None);
    }

    /// Same contract as above, for `workshop_id`: a report cached before this
    /// field existed must still deserialize, defaulting to `None`.
    #[test]
    fn a_mod_json_from_before_the_workshop_id_field_existed_still_deserializes() {
        let json = r#"{
            "id": "sample.mod",
            "name": "Sample Mod",
            "authors": [],
            "url": null,
            "path": "SampleMod",
            "source": "local",
            "supported_versions": [],
            "declared": {
                "load_after": [], "load_before": [], "force_load_after": [],
                "force_load_before": [], "dependencies": [], "incompatible_with": []
            },
            "loaded_folders": [],
            "hard_dependents": 0,
            "soft_dependents": 0,
            "awareness_dependents": 0,
            "is_framework_candidate": false
        }"#;

        let mod_entry: Mod =
            serde_json::from_str(json).expect("must deserialize without `workshop_id`");

        assert_eq!(mod_entry.workshop_id, None);
    }

    /// Same contract, for `load_folders_version_matched`: a report cached
    /// before this field existed must still deserialize, defaulting to `None`
    /// — see [`super::REPORT_SCHEMA_VERSION`]'s own doc comment for why a
    /// *consumer* must still treat that as stale rather than trust it.
    #[test]
    fn a_mod_json_from_before_the_load_folders_version_matched_field_existed_still_deserializes() {
        let json = r#"{
            "id": "sample.mod",
            "name": "Sample Mod",
            "authors": [],
            "url": null,
            "path": "SampleMod",
            "source": "local",
            "supported_versions": [],
            "declared": {
                "load_after": [], "load_before": [], "force_load_after": [],
                "force_load_before": [], "dependencies": [], "incompatible_with": []
            },
            "loaded_folders": [],
            "hard_dependents": 0,
            "soft_dependents": 0,
            "awareness_dependents": 0,
            "is_framework_candidate": false
        }"#;

        let mod_entry: Mod = serde_json::from_str(json)
            .expect("must deserialize without `load_folders_version_matched`");

        assert_eq!(mod_entry.load_folders_version_matched, None);
    }
}
