//! Shared by `examples/gen_patch_export_fixture.rs` and
//! `tests/patch_export_golden.rs`: the compat-patch scenario both render —
//! the `merge_game` fixture's `Fixture_Wall` (`ModA`/`ModB`), scope
//! `{fixture.moda, fixture.modb}`, one field choice.

use std::collections::{BTreeMap, BTreeSet};

use rim_analyzer::domain::ModId;
use rim_merge::diff::{OwnerVersion, three_way};
use rim_merge::emit::{AboutSpec, Dependencies, EmitInput, GeneratedModIdentity, Provenance};
use rim_merge::plan::{MergeChoice, MergePlan, plan_def_override};
use rim_merge::tree::FieldPath;
use rim_merge::xml;

const MODA: &str = "fixture.moda";
const MODB: &str = "fixture.modb";

fn owner(id: &str, xml_text: &str) -> OwnerVersion {
    let tree = xml::parse(xml_text).unwrap_or_else(|error| panic!("{id}: {error:?}"));
    OwnerVersion {
        mod_id: ModId::new(id),
        raw: tree.clone(),
        resolved: tree,
        inherited: None,
    }
}

/// Everything [`Scenario::input`] needs, owned — [`EmitInput`] only ever
/// borrows from it, so the scenario outlives every render built from it.
pub struct Scenario {
    identity: GeneratedModIdentity,
    description: String,
    plans: Vec<MergePlan>,
    mod_names: BTreeMap<ModId, String>,
    scope: BTreeSet<ModId>,
}

impl Scenario {
    /// Borrows an [`EmitInput`] for this scenario — a compat patch export,
    /// `Dependencies::Exactly` the scope, `Provenance::CompatPatch`.
    pub fn input(&self) -> EmitInput<'_> {
        EmitInput {
            about: AboutSpec {
                identity: &self.identity,
                author: "sample",
                description: &self.description,
                dependencies: Dependencies::Exactly(&self.scope),
            },
            game_version: "1.6",
            plans: &self.plans,
            defs: &[],
            assets: &[],
            mod_names: &self.mod_names,
            provenance: Provenance::CompatPatch {
                patch_id: "3f9a1c02be77",
                profile_hash: "3f9a1c2b7d5e",
                scope: &self.scope,
                decisions_sha256: "9f1c2a7b3e5d",
            },
            rimmerge_version: "0.1.0",
        }
    }
}

/// Builds the scenario: `ModA`'s `Fixture_Wall` (`statBases/MaxHitPoints`
/// 150, the diff's base) versus `ModB`'s (300, and a different label, the
/// load order's winner); the patch's one choice picks `ModA`'s hit points
/// back over `ModB`'s — the only field this patch actually touches (the
/// differing `label` resolves to the winner's own value automatically, so
/// it needs no op).
pub fn build() -> Scenario {
    let moda = owner(
        MODA,
        r#"<ThingDef><defName>Fixture_Wall</defName><label>fixture wall</label><category>Building</category><passability>Impassable</passability><statBases><MaxHitPoints>150</MaxHitPoints></statBases></ThingDef>"#,
    );
    let modb = owner(
        MODB,
        r#"<ThingDef><defName>Fixture_Wall</defName><label>reinforced fixture wall</label><category>Building</category><passability>Impassable</passability><statBases><MaxHitPoints>300</MaxHitPoints></statBases></ThingDef>"#,
    );

    let diff = three_way(&[moda.clone(), modb.clone()], &ModId::new(MODA))
        .unwrap_or_else(|error| panic!("{error:?}"));
    let max_hit_points: FieldPath = "statBases/MaxHitPoints"
        .parse()
        .unwrap_or_else(|error| panic!("{error:?}"));
    let choices: BTreeMap<FieldPath, MergeChoice> = [(
        max_hit_points,
        MergeChoice::From {
            mod_id: ModId::new(MODA),
        },
    )]
    .into_iter()
    .collect();
    let plan = plan_def_override(&diff, &modb, &choices);
    assert!(
        plan.unresolved.is_empty(),
        "the fixture scenario has a choice for its one conflict: {:?}",
        plan.caveats
    );
    assert_eq!(plan.ops.len(), 1, "exactly the MaxHitPoints override");

    let mut mod_names = BTreeMap::new();
    mod_names.insert(ModId::new(MODA), "Fixture Mod A".to_string());
    mod_names.insert(ModId::new(MODB), "Fixture Mod B".to_string());
    let scope: BTreeSet<ModId> = [ModId::new(MODA), ModId::new(MODB)].into_iter().collect();

    Scenario {
        identity: GeneratedModIdentity {
            package_id: ModId::new("sample.abcompat"),
            folder_name: "sample_abcompat".to_string(),
            display_name: "A + B Compatibility".to_string(),
        },
        description: "Compatibility patch for Fixture Mod A, Fixture Mod B, generated by Rimmerge from field-level merge decisions. Every patch operation is gated with MayRequire on the mods it depends on.".to_string(),
        plans: vec![plan],
        mod_names,
        scope,
    }
}
