// Every Tauri command wrapper, re-exported from one module per domain.

export {
  addAssignmentSection,
  clearAssignmentRow,
  copyAssignmentRowFrom,
  createAssignment,
  deleteAssignment,
  exportAssignment,
  getAssignment,
  getAssignmentCoverage,
  inferAssignmentCandidate,
  listAssignmentCandidates,
  listAssignmentItems,
  listAssignments,
  removeAssignmentSection,
  setAssignmentRow,
  updateAssignment,
} from "./ipc/assignments";
export { RimmergeError, setSessionLostHandler } from "./ipc/core";
export {
  decide,
  getDefConflictView,
  getFinding,
  inspectDef,
  listFindings,
  listModChanges,
  readDefTexture,
  resolveDefGraphic,
  revertDecision,
  searchDefs,
} from "./ipc/findings";
export { getGameLaunchStatus, launchGame } from "./ipc/gameLaunch";
export {
  getMergeMod,
  getMergePreview,
  previewMergeModFile,
  readTexture,
  setMergeChoices,
} from "./ipc/merge";
export {
  checkForUpdate,
  completeWelcome,
  dismissNotification,
  listMutedNotificationKinds,
  listNotifications,
  muteNotificationKind,
  resetSettings,
  runLaunchNetworkChecks,
  unmuteNotificationKind,
} from "./ipc/notifications";
export {
  exportOrderFile,
  exportOrderText,
  importOrder,
  openWorkshopPage,
  previewOrderImportFile,
  previewOrderImportText,
  suggestedModListPath,
} from "./ipc/orderShare";
export {
  createPatch,
  decidePatch,
  deletePatch,
  exportPatch,
  getPatch,
  getPatchFinding,
  getPatchRender,
  importProfileDecisions,
  listPatches,
  listPatchFindings,
  previewPatchFile,
  prunePatchDecisions,
  revertPatchDecision,
  updatePatch,
} from "./ipc/patches";
export {
  activateMods,
  apply,
  deactivateMods,
  enableRecommendedRuleDatabases,
  explainPlacement,
  getApplyPreflight,
  getAppSettings,
  getAppVersion,
  getDashboard,
  getDefaultPaths,
  getDefaultRimSortPaths,
  getDefaultSettings,
  getDefCacheCarrier,
  getMod,
  getModInfo,
  getPendingActiveChanges,
  getSettings,
  getStartupCosts,
  importGameLog,
  listInactiveMods,
  listModNames,
  listMods,
  listOrder,
  loadProject,
  openAppLink,
  openModLink,
  planActivateMods,
  planDeactivateMods,
  readModIcon,
  readModPreview,
  rescanProject,
  resetNetworkPolicy,
  saveAppConfig,
  selectOrder,
  setSettings,
  updateAppSettings,
} from "./ipc/project";
export {
  deleteRule,
  getRecommendedRules,
  getRecommendedRulesStep,
  getRuleDatabases,
  importRimSort,
  listOrphanedDecisions,
  listRules,
  listTags,
  promoteImportedRule,
  refreshRuleDatabases,
  setManualTag,
  skipRecommendedRulesStep,
  upsertRule,
} from "./ipc/rules";
export { verifyOrder } from "./ipc/verify";
