//! [`CreatePatch`]: validates and builds a new compat patch project,
//! persisting it through [`PatchProjectStore`] before making it visible on
//! the session.

use std::collections::BTreeSet;

use rim_analyzer::domain::ModId;
use rim_resolve::domain::{
    PatchId, PatchIdentityError, PatchModIdentity, PatchProject, PatchScope, PatchScopeError,
};

use crate::Session;
use crate::ports::{PatchProjectStore, StoreError};

/// A new patch's requested shape, straight from the interface layer
/// (already-parsed, unvalidated) — `create_patch`'s own request DTO in
/// the desktop/CLI, one level up.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CreatePatchInput {
    /// The project's label in lists (see
    /// [`PatchProject::name`]/[`PatchProject::set_name`]).
    pub name: String,
    /// The published mod's package id (validated by
    /// [`PatchModIdentity::new`]).
    pub package_id: String,
    /// The published mod's display name.
    pub display_name: String,
    /// The patch scope's members.
    pub scope: BTreeSet<ModId>,
}

/// Everything that can go wrong creating a patch.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum CreatePatchError {
    /// `package_id`/`display_name` failed
    /// [`PatchModIdentity::new`]'s own validation.
    #[error(transparent)]
    Identity(#[from] PatchIdentityError),
    /// Fewer than two distinct scope members were given.
    #[error(transparent)]
    Scope(#[from] PatchScopeError),
    /// A scope member isn't currently active.
    #[error("{0} is not an active mod")]
    InactiveScopeMember(ModId),
    /// A scope member is a Rimmerge-generated mod (the profile merge mod,
    /// or another compat patch) — a patch can't be *about* a mod Rimmerge
    /// itself made.
    #[error("{0} is a Rimmerge-generated mod and can't be a patch scope member")]
    GeneratedScopeMember(ModId),
    /// `package_id` collides with an active mod's base id or another
    /// project's own package id.
    #[error("package id {0} is already used by an active mod or another patch")]
    PackageIdTaken(ModId),
    /// Persisting the new project failed.
    #[error("saving the patch: {0}")]
    Store(StoreError),
}

/// The `About.xml` description template a newly created patch gets by
/// default, naming each scope
/// member's display name — in [`rim_resolve::domain::PatchScope::members`]'s
/// own id-sorted order, the only order the domain type carries (it holds a
/// set, not a user-ordered list).
///
/// Keyed by [`ModId::base`], not the report's own raw id: `scope.members()`
/// always holds base ids (declared ids never carry `_steam` — see this
/// crate's own `CLAUDE.md`), so a scope member installed through Steam
/// Workshop (whose `report().mods` entry carries the `_steam`-suffixed
/// id) would otherwise never match here and silently fall back to
/// printing its bare id instead of its actual display name.
fn default_description(session: &Session, scope: &PatchScope) -> String {
    let names_by_id: std::collections::BTreeMap<ModId, &str> = session
        .report()
        .mods
        .iter()
        .map(|m| (m.id.base(), m.name.as_str()))
        .collect();
    let names: Vec<&str> = scope
        .members()
        .iter()
        .map(|id| names_by_id.get(id).copied().unwrap_or_else(|| id.as_str()))
        .collect();
    format!(
        "Compatibility patch for {}, generated by Rimmerge from field-level merge decisions. \
         Every patch operation is gated with MayRequire on the mods it depends on.",
        names.join(", ")
    )
}

/// Validates and builds a new [`PatchProject`], persists it, then makes it
/// visible on the session.
pub struct CreatePatch<Store> {
    store: Store,
}

impl<Store: PatchProjectStore> CreatePatch<Store> {
    /// Builds the use case from its port.
    #[must_use]
    pub fn new(store: Store) -> Self {
        Self { store }
    }

    /// Validates `input` against the session's current active mods and
    /// reserved package ids, builds the project (default author
    /// `"Rimmerge"`, the default description template), saves it, and
    /// makes it visible on `session`.
    ///
    /// # Errors
    ///
    /// See [`CreatePatchError`]. Nothing changes on `session` when this
    /// returns an error — the project is only made visible once it has
    /// been persisted.
    pub fn execute(
        &self,
        session: &mut Session,
        input: CreatePatchInput,
    ) -> Result<PatchId, CreatePatchError> {
        let identity = PatchModIdentity::new(&input.package_id, &input.display_name)?;

        let active = session.active_base_ids();
        let reserved = session.reserved_package_ids();
        for mod_id in &input.scope {
            let base = mod_id.base();
            if !active.contains(&base) {
                return Err(CreatePatchError::InactiveScopeMember(mod_id.clone()));
            }
            if reserved.contains(&base) {
                return Err(CreatePatchError::GeneratedScopeMember(mod_id.clone()));
            }
        }
        let scope = PatchScope::new(input.scope)?;

        let package_base = identity.package_id().base();
        if active.contains(&package_base) || reserved.contains(&package_base) {
            return Err(CreatePatchError::PackageIdTaken(
                identity.package_id().clone(),
            ));
        }

        let created_at = jiff::Timestamp::now();
        let profile_hash = session.paths().profile_hash().to_string();
        let id = PatchId::derive(&profile_hash, identity.package_id(), created_at);
        let mut project = PatchProject::new(id.clone(), input.name, identity, scope, created_at);
        let description = default_description(session, project.scope());
        project.set_description(description);

        if let Err(error) = self.store.save(&session.paths().profile_dir, &project) {
            return Err(CreatePatchError::Store(error));
        }
        session.upsert_patch(project);
        Ok(id)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::test_support::{
        InMemoryPatchProjectStore, session_fixture, session_fixture_with_generated,
    };

    fn input(scope: &[&str]) -> CreatePatchInput {
        CreatePatchInput {
            name: "AB compat".to_string(),
            package_id: "sample.abcompat".to_string(),
            display_name: "A + B Compatibility".to_string(),
            scope: scope.iter().map(|id| ModId::new(*id)).collect(),
        }
    }

    #[test]
    fn creates_and_persists_a_valid_patch() {
        let mut session = session_fixture(&["a", "b"]);
        let store = InMemoryPatchProjectStore::new();
        let use_case = CreatePatch::new(store);

        let id = use_case
            .execute(&mut session, input(&["a", "b"]))
            .expect("a valid patch must be created");

        let project = session.patch(&id).expect("the project must be visible");
        assert_eq!(project.name(), "AB compat");
        assert_eq!(
            project.identity().package_id(),
            &ModId::new("sample.abcompat")
        );
        assert!(
            project.description().contains("Compatibility patch for"),
            "{}",
            project.description()
        );
        assert!(use_case.store.last_saved(&id).is_some());
    }

    /// A scope member installed through Steam Workshop carries a
    /// `_steam`-suffixed id in the report, while `scope.members()` (and
    /// this test's own `input`) always names the *base* id — the
    /// description template must still resolve that member's real display
    /// name, not fall back to printing its bare id.
    #[test]
    fn the_default_description_resolves_a_steam_installed_scope_members_name() {
        let report = rim_resolve::test_support::ReportBuilder::new()
            .mod_with("a_steam", |m| m.name = "A Mod (Steam)".to_string())
            .mod_("b")
            .build();
        let mut session = Session::new(
            crate::ProjectPaths {
                game_dir: "game".into(),
                workshop_dir: "workshop".into(),
                mods_config: "ModsConfig.xml".into(),
                profile_dir: "profile".into(),
            },
            report,
            Vec::new(),
            rim_analyzer::analysis::SourceIndex::default(),
            crate::ports::StoredRules::default(),
            rim_resolve::domain::DecisionSet::new(),
            crate::ports::ModsConfigFile {
                version: "1.6".to_string(),
                active_mods: vec![ModId::new("a_steam"), ModId::new("b")],
                known_expansions: Vec::new(),
            },
            Vec::new(),
            Vec::new(),
        );
        let use_case = CreatePatch::new(InMemoryPatchProjectStore::new());

        let id = use_case
            .execute(&mut session, input(&["a", "b"]))
            .expect("a valid patch must be created");

        let project = session.patch(&id).expect("the project must be visible");
        assert!(
            project.description().contains("A Mod (Steam)"),
            "must resolve the Steam-installed member's real display name, not its bare id: {}",
            project.description()
        );
    }

    #[test]
    fn rejects_an_invalid_package_id() {
        let mut session = session_fixture(&["a", "b"]);
        let use_case = CreatePatch::new(InMemoryPatchProjectStore::new());
        let mut bad_input = input(&["a", "b"]);
        bad_input.package_id = "no_author_segment".to_string();

        let result = use_case.execute(&mut session, bad_input);

        assert!(matches!(result, Err(CreatePatchError::Identity(_))));
    }

    #[test]
    fn rejects_a_scope_with_fewer_than_two_members() {
        let mut session = session_fixture(&["a", "b"]);
        let use_case = CreatePatch::new(InMemoryPatchProjectStore::new());

        let result = use_case.execute(&mut session, input(&["a"]));

        assert!(matches!(result, Err(CreatePatchError::Scope(_))));
    }

    #[test]
    fn rejects_an_inactive_scope_member() {
        let mut session = session_fixture(&["a", "b"]);
        let use_case = CreatePatch::new(InMemoryPatchProjectStore::new());

        let result = use_case.execute(&mut session, input(&["a", "gone"]));

        assert_eq!(
            result,
            Err(CreatePatchError::InactiveScopeMember(ModId::new("gone")))
        );
    }

    /// A report-marked generated mod (the profile merge mod, or another
    /// patch's own export) can never be picked as a new patch's scope
    /// member, even though it's active — `reserved_package_ids` must
    /// catch it before `PatchScope::new` ever runs.
    #[test]
    fn rejects_a_generated_scope_member() {
        let mut session = session_fixture_with_generated(&["a", "gen.mod"], "gen.mod");
        let use_case = CreatePatch::new(InMemoryPatchProjectStore::new());

        let result = use_case.execute(&mut session, input(&["a", "gen.mod"]));

        assert_eq!(
            result,
            Err(CreatePatchError::GeneratedScopeMember(ModId::new(
                "gen.mod"
            )))
        );
    }

    #[test]
    fn rejects_a_package_id_already_used_by_an_active_mod() {
        // A valid package id needs an author segment (`.`), so the
        // clashing active mod must have one too — a bare `"a"` id could
        // never collide with a syntactically valid `package_id` in the
        // first place.
        let mut session = session_fixture(&["vendor.moda", "b"]);
        let use_case = CreatePatch::new(InMemoryPatchProjectStore::new());
        let mut clashing_input = input(&["vendor.moda", "b"]);
        clashing_input.package_id = "vendor.moda".to_string();

        let result = use_case.execute(&mut session, clashing_input);

        assert!(matches!(result, Err(CreatePatchError::PackageIdTaken(_))));
    }

    #[test]
    fn rejects_a_package_id_already_used_by_another_patch() {
        let mut session = session_fixture(&["a", "b", "c"]);
        CreatePatch::new(InMemoryPatchProjectStore::new())
            .execute(&mut session, input(&["a", "b"]))
            .expect("the first patch must be created");
        let use_case = CreatePatch::new(InMemoryPatchProjectStore::new());
        let second_input = CreatePatchInput {
            name: "second".to_string(),
            package_id: "sample.abcompat".to_string(),
            display_name: "Another Name".to_string(),
            scope: [ModId::new("b"), ModId::new("c")].into_iter().collect(),
        };

        let result = use_case.execute(&mut session, second_input);

        assert!(matches!(result, Err(CreatePatchError::PackageIdTaken(_))));
    }

    #[test]
    fn a_failed_save_never_makes_the_patch_visible() {
        let mut session = session_fixture(&["a", "b"]);
        let store = InMemoryPatchProjectStore::new();
        store.fail_next_save();
        let use_case = CreatePatch::new(store);

        let result = use_case.execute(&mut session, input(&["a", "b"]));

        assert!(matches!(result, Err(CreatePatchError::Store(_))));
        assert_eq!(session.patches().count(), 0);
    }
}
