//! Shared folder-safety and install core behind both [`super::ExportPatch`]
//! and [`super::ExportAssignment`]:
//! absolute-`out_dir`/inside-`Mods/` path checks, "is this folder already
//! my own previous export" marker refusal, and the install-into-`Mods/` +
//! `ModsConfig.xml` write-with-backup + [`Session::set_current_order`]
//! bookkeeping [`ExportPatch::execute`]'s own `install` option and
//! [`super::ExportAssignment::execute`]'s twin both need.
//!
//! Extracted from `export_patch.rs`, **behaviour-preserving**: every
//! `ExportPatch` test still passes unmodified — only its own imports
//! moved to reach these functions instead of file-local ones. The running-
//! game refusal itself stays out of scope for both, exactly as before:
//! this crate has no process access (see `crates/rim-session/CLAUDE.md`),
//! that check is the interface layer's own job.

use std::path::{Component, Path, PathBuf};

use rim_analyzer::domain::{GeneratedKind, GeneratedMarker, LoadOrder, ModId};
use rim_merge::emit::RenderedMod;

use crate::Session;
use crate::ports::{ConfigError, MergeModError, MergeModWriter, ModsConfigStore};

/// Windows' extended-length path prefix, stripped so a canonicalized
/// (`\\?\C:\...`) and a plain (`C:\...`) spelling of the same path compare
/// equal — mirrors `rim_io::profile_dir`'s own normalization (duplicated
/// rather than shared: this crate does no filesystem IO of its own, and
/// that one lives in the `rim-io` adapter this crate can't depend on).
const EXTENDED_PREFIX: &str = r"\\?\";

/// Lexically resolves `path`'s `.`/`..` components, strips
/// [`EXTENDED_PREFIX`], and lowercases with forward slashes throughout —
/// entirely in memory, so unlike `rim_io::profile_dir`'s own
/// normalization this never calls `Path::canonicalize` (a filesystem
/// read this crate's own `CLAUDE.md` forbids) and so never resolves a
/// symlink, a junction, or an 8.3 short name. Resolving those is the
/// interface layer's job, before a path ever reaches either export use
/// case — the same boundary that already hands back an absolute path
/// (each use case's own `OutDirNotAbsolute` refuses anything else) —
/// exactly the kind of client-side safety check a sufficiently determined
/// caller can still walk past.
pub(crate) fn normalize_lexically(path: &Path) -> String {
    let mut prefix = String::new();
    let mut parts: Vec<String> = Vec::new();
    for component in path.components() {
        match component {
            Component::Prefix(prefix_component) => {
                prefix = prefix_component.as_os_str().to_string_lossy().into_owned();
            }
            Component::RootDir | Component::CurDir => {}
            Component::ParentDir => {
                parts.pop();
            }
            Component::Normal(part) => parts.push(part.to_string_lossy().into_owned()),
        }
    }
    let joined = parts.join("/");
    let full = match (prefix.is_empty(), joined.is_empty()) {
        (true, _) => joined,
        (false, true) => prefix,
        (false, false) => format!("{prefix}/{joined}"),
    };
    let stripped = full.strip_prefix(EXTENDED_PREFIX).unwrap_or(&full);
    stripped.replace('\\', "/").to_lowercase()
}

/// Whether `path` is `ancestor` or lives under it, comparing each side's
/// own [`normalize_lexically`] text.
pub(crate) fn is_inside(path: &Path, ancestor: &Path) -> bool {
    let path_text = normalize_lexically(path);
    let ancestor_text = normalize_lexically(ancestor);
    let ancestor_text = ancestor_text.trim_end_matches('/');
    path_text == ancestor_text || path_text.starts_with(&format!("{ancestor_text}/"))
}

/// `<profile>/<kind_dir>/<id>.<suffix>/` — the one backup folder
/// [`MergeModWriter::write`] keeps for one project's own export into one
/// location (`"prev"` for the user's own `out_dir`, `"installed.prev"` for
/// the game's `Mods/`) — two independent backup slots, since the same
/// rendered folder can be written to both locations independently.
/// `kind_dir` is `"patches"`/`"assignments"`, matching each project kind's
/// own store directory.
pub(crate) fn backup_dir(session: &Session, kind_dir: &str, id: &str, suffix: &str) -> PathBuf {
    session
        .paths()
        .profile_dir
        .join(kind_dir)
        .join(format!("{id}.{suffix}"))
}

/// The folder at `dir/folder_name` already exists and isn't the caller's
/// own previous export.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
#[error("{path} already exists and wasn't generated by this project", path = path.display())]
pub(crate) struct ForeignFolderError {
    pub(crate) path: PathBuf,
}

/// A [`ForeignFolderError`], or the marker read itself failed.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub(crate) enum EnsureNotForeignError {
    /// The folder exists and isn't this project's own.
    #[error(transparent)]
    Foreign(#[from] ForeignFolderError),
    /// Reading the folder's own marker failed.
    #[error(transparent)]
    Read(#[from] MergeModError),
}

/// Refuses when `<dir>/<folder_name>` already exists and its marker isn't
/// this project's own (absent, or naming `expected_kind`/`expected_id` —
/// the same field slot [`GeneratedMarker::patch_id`] carries for both a
/// compat patch's id and an assignment project's id).
pub(crate) fn ensure_not_foreign<Writer: MergeModWriter>(
    writer: &Writer,
    dir: &Path,
    folder_name: &str,
    expected_kind: GeneratedKind,
    expected_id: &str,
) -> Result<(), EnsureNotForeignError> {
    if !writer.exists(dir, folder_name) {
        return Ok(());
    }
    let marker = writer.read_marker(dir, folder_name)?;
    let is_own = matches!(&marker,
        Some(GeneratedMarker {
            kind,
            patch_id: Some(marker_id),
            ..
        }) if *kind == expected_kind && marker_id.as_str() == expected_id
    );
    if is_own {
        Ok(())
    } else {
        Err(ForeignFolderError {
            path: dir.join(folder_name),
        }
        .into())
    }
}

/// Writing the rendered folder into `Mods/`, or writing `ModsConfig.xml`
/// with its backup, failed.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub(crate) enum InstallError {
    /// Writing the rendered folder failed.
    #[error(transparent)]
    Write(#[from] MergeModError),
    /// Writing `ModsConfig.xml` failed.
    #[error(transparent)]
    Config(#[from] ConfigError),
}

/// What [`install`] did.
pub(crate) struct InstallOutcome {
    pub(crate) installed_path: PathBuf,
    pub(crate) mods_config_backup: PathBuf,
}

/// Copies `rendered` into `mods_dir` and appends `package_id` to the
/// **current** `ModsConfig.xml` order (not the selected one — install is
/// not apply), if absent, then calls [`Session::set_current_order`] so the
/// in-memory session matches the file just written. The foreign-folder
/// check for `mods_dir` is the caller's own job, run before the first
/// write to either location — see [`super::export_patch::ExportPatch::execute`]/
/// [`super::export_assignment::ExportAssignment::execute`] for that
/// ordering.
pub(crate) fn install<Writer: MergeModWriter, Config: ModsConfigStore>(
    writer: &Writer,
    config_store: &Config,
    session: &mut Session,
    mods_dir: &Path,
    backup_dir: &Path,
    rendered: &RenderedMod,
    package_id: &ModId,
) -> Result<InstallOutcome, InstallError> {
    let install_report = writer.write(mods_dir, backup_dir, rendered)?;

    let mut order = session.orders().current.as_slice().to_vec();
    if !order.contains(package_id) {
        order.push(package_id.clone());
    }
    let load_order = LoadOrder::new(order);
    let file = session.mods_config_file_for(&load_order);
    let mods_config_backup = config_store.write_with_backup(&session.paths().mods_config, &file)?;
    // Keep the in-memory session in sync with the file just written —
    // otherwise a later `Apply { write_mods_config: true }` with
    // `selected() == OrderSource::Current` would read the *stale*
    // `current` (missing this package id) and write it straight back,
    // silently deactivating whatever this write just appended
    // (`Session::set_current_order`'s own doc comment).
    session.set_current_order(load_order);

    Ok(InstallOutcome {
        installed_path: install_report.mod_path,
        mods_config_backup,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn is_inside_resolves_a_parent_dir_segment_before_comparing() {
        assert!(is_inside(
            Path::new(r"C:\game\Other\..\Mods\x"),
            Path::new(r"C:\game\Mods")
        ));
    }

    #[test]
    fn is_inside_is_case_and_slash_insensitive() {
        assert!(is_inside(
            Path::new("C:/GAME/mods/x"),
            Path::new(r"c:\game\Mods")
        ));
    }

    #[test]
    fn is_inside_treats_a_verbatim_prefixed_path_the_same_as_a_plain_one() {
        assert!(is_inside(
            Path::new(r"\\?\C:\game\Mods\x"),
            Path::new(r"C:\game\Mods")
        ));
        assert!(is_inside(
            Path::new(r"C:\game\Mods\x"),
            Path::new(r"\\?\C:\game\Mods")
        ));
    }

    #[test]
    fn is_inside_is_false_for_a_sibling_folder() {
        assert!(!is_inside(
            Path::new(r"C:\game\ModsBackup\x"),
            Path::new(r"C:\game\Mods")
        ));
    }

    /// A relative `Mods/x` never satisfies either use case's own
    /// `OutDirNotAbsolute` refusal, but `is_inside` itself is a pure text
    /// comparison with no opinion on absoluteness — it still resolves and
    /// compares correctly.
    #[test]
    fn is_inside_compares_relative_paths_lexically_too() {
        assert!(is_inside(Path::new("Mods/x"), Path::new("Mods")));
        assert!(!is_inside(Path::new("Mods/x"), Path::new("Other")));
    }
}
