//! [`ExportPatch`]: renders one compat patch's own merge mod candidate and
//! writes it to a user-chosen folder — never `<game>/Mods` by default —
//! optionally installing (copying the same rendered folder into `Mods/`
//! and activating it).

use std::path::{Path, PathBuf};

use rim_analyzer::domain::GeneratedKind;
use rim_merge::emit::RenderedMod;
use rim_resolve::domain::{FindingKey, PatchId};

use super::export_folder::{self, EnsureNotForeignError, ForeignFolderError, InstallError};
use super::render_merge_mod::RenderMergeModError;
use super::render_patch::{RenderPatch, RenderPatchError};
use crate::ports::{
    AssetLocator, ConfigError, DefSourceReader, MergeModError, MergeModWriter, ModsConfigStore,
    PatchProjectStore, StoreError,
};
use crate::{Session, UnknownPatch};

/// Where an export lands, and whether it should also be installed.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ExportOptions {
    /// The folder to render the patch into — never `<game>/Mods` or a
    /// subfolder of it (see [`ExportPatchError::OutDirIsModsFolder`]).
    pub out_dir: PathBuf,
    /// Also copy the same rendered folder into `<game>/Mods` and activate
    /// it (append its package id to the current `ModsConfig.xml` order, if
    /// absent). The running-game refusal/`force` gate is the interface
    /// layer's own job — this use case has no process access
    /// and never checks it.
    pub install: bool,
}

/// What [`ExportPatch::execute`] did.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ExportOutcome {
    /// `<out_dir>/<folder_name>` — where the patch was written.
    pub export_path: PathBuf,
    /// `<game>/Mods/<folder_name>`, when [`ExportOptions::install`] copied
    /// the same rendered folder there.
    pub installed_path: Option<PathBuf>,
    /// The `ModsConfig.xml` backup path, when `install` wrote it.
    pub mods_config_backup: Option<PathBuf>,
    /// `Merge`/`ShipAsset` decisions skipped because their preview wasn't
    /// complete, or their asset couldn't be located — the export still
    /// went ahead without them, exactly as [`super::Apply`] reports.
    pub skipped: Vec<FindingKey>,
    /// Every written file's path, relative to [`Self::export_path`].
    pub files: Vec<PathBuf>,
    /// The canonical hash of the decisions this export was built from
    /// ([`rim_resolve::domain::PatchProject::decisions_sha256`]).
    pub decisions_sha256: String,
}

/// Everything that can go wrong exporting a patch.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum ExportPatchError {
    /// No patch project with the given id is loaded.
    #[error(transparent)]
    Unknown(#[from] UnknownPatch),
    /// Rendering the patch failed.
    #[error(transparent)]
    Render(#[from] RenderMergeModError),
    /// The rendered patch has no complete merge and no located asset —
    /// there is nothing to write.
    #[error("this patch has no complete merge or located asset to export")]
    NothingToExport,
    /// `out_dir` is, or is inside, the game's `Mods` folder — refused;
    /// [`ExportOptions::install`] is the only sanctioned way to write
    /// there.
    #[error("{0} is inside the game's Mods folder; use install instead")]
    OutDirIsModsFolder(PathBuf),
    /// `out_dir` isn't absolute. A relative path has no well-defined
    /// location once this use case (no filesystem access of its own — see
    /// this crate's `CLAUDE.md`) can't resolve it against a working
    /// directory; the interface layer's own folder picker always returns
    /// an absolute path, so this only fires against a hand-typed one.
    #[error("{0} must be an absolute path")]
    OutDirNotAbsolute(PathBuf),
    /// The target folder already exists and isn't this patch's own
    /// previous export (no marker, the profile merge mod's marker, or
    /// another patch's).
    #[error("{path} already exists and wasn't generated by this patch", path = path.display())]
    ForeignFolder {
        /// The folder that already exists and isn't this patch's own.
        path: PathBuf,
    },
    /// Writing the rendered folder failed.
    #[error(transparent)]
    Write(#[from] MergeModError),
    /// Persisting the export target on the patch project failed. The files
    /// already written to disk are **not** rolled back — only the
    /// project's own `export_dir` bookkeeping is (see
    /// [`Session::restore_patch`]).
    #[error("saving the patch: {0}")]
    Store(StoreError),
    /// Writing `ModsConfig.xml` during install failed.
    #[error(transparent)]
    Config(#[from] ConfigError),
}

impl From<RenderPatchError> for ExportPatchError {
    fn from(error: RenderPatchError) -> Self {
        match error {
            RenderPatchError::Unknown(unknown) => Self::Unknown(unknown),
            RenderPatchError::Render(render) => Self::Render(render),
        }
    }
}

impl From<EnsureNotForeignError> for ExportPatchError {
    fn from(error: EnsureNotForeignError) -> Self {
        match error {
            EnsureNotForeignError::Foreign(ForeignFolderError { path }) => {
                Self::ForeignFolder { path }
            }
            EnsureNotForeignError::Read(error) => Self::Write(error),
        }
    }
}

impl From<InstallError> for ExportPatchError {
    fn from(error: InstallError) -> Self {
        match error {
            InstallError::Write(error) => Self::Write(error),
            InstallError::Config(error) => Self::Config(error),
        }
    }
}

/// Renders `id`'s own merge mod candidate and writes it into a user-chosen
/// folder, optionally installing the same rendered folder into the game's
/// `Mods/` and activating it.
pub struct ExportPatch<Writer, Reader, Assets, Config, Store> {
    writer: Writer,
    render: RenderPatch<Reader, Assets>,
    config_store: Config,
    store: Store,
}

impl<Writer, Reader, Assets, Config, Store> ExportPatch<Writer, Reader, Assets, Config, Store>
where
    Writer: MergeModWriter,
    Reader: DefSourceReader,
    Assets: AssetLocator,
    Config: ModsConfigStore,
    Store: PatchProjectStore,
{
    /// Builds the use case from its ports.
    #[must_use]
    pub fn new(
        writer: Writer,
        reader: Reader,
        asset_locator: Assets,
        config_store: Config,
        store: Store,
    ) -> Self {
        Self {
            writer,
            render: RenderPatch::new(reader, asset_locator),
            config_store,
            store,
        }
    }

    /// Renders, writes, and (when asked) installs `id`'s patch. Each step
    /// fails without touching the next: nothing under the game directory
    /// is ever written unless `options.install` is set, and a failure
    /// persisting `export_dir` never touches the files already on disk.
    ///
    /// # Errors
    ///
    /// See [`ExportPatchError`].
    pub fn execute(
        &self,
        session: &mut Session,
        id: &PatchId,
        options: ExportOptions,
    ) -> Result<ExportOutcome, ExportPatchError> {
        if !options.out_dir.is_absolute() {
            return Err(ExportPatchError::OutDirNotAbsolute(options.out_dir));
        }

        let render = self.render.execute(session, id)?;
        let Some(rendered) = render.rendered else {
            return Err(ExportPatchError::NothingToExport);
        };

        let mods_dir = session.paths().game_dir.join("Mods");
        if export_folder::is_inside(&options.out_dir, &mods_dir) {
            return Err(ExportPatchError::OutDirIsModsFolder(options.out_dir));
        }
        // Both refusals happen before the first write (below) — an
        // `install` whose *target* folder is foreign must not leave
        // behind a write to `out_dir` or a persisted `export_dir` from
        // getting that far first.
        export_folder::ensure_not_foreign(
            &self.writer,
            &options.out_dir,
            &rendered.folder_name,
            GeneratedKind::Patch,
            id.as_str(),
        )?;
        if options.install {
            export_folder::ensure_not_foreign(
                &self.writer,
                &mods_dir,
                &rendered.folder_name,
                GeneratedKind::Patch,
                id.as_str(),
            )?;
        }

        let backup_dir = export_folder::backup_dir(session, "patches", id.as_str(), "prev");
        let report = self
            .writer
            .write(&options.out_dir, &backup_dir, &rendered)?;

        let snapshot = session.patch_snapshot(id).unwrap_or_else(|| {
            unreachable!("rendering above already confirmed the patch is loaded")
        });
        let mut updated = snapshot.clone();
        updated.set_export_dir(Some(options.out_dir.clone()));
        session.upsert_patch(updated);
        if let Err(error) = self.store.save(
            &session.paths().profile_dir,
            session
                .patch(id)
                .unwrap_or_else(|| unreachable!("just upserted above")),
        ) {
            session.restore_patch(snapshot);
            return Err(ExportPatchError::Store(error));
        }

        let (installed_path, mods_config_backup) =
            self.maybe_install(session, id, &options, &mods_dir, &rendered)?;

        let files = rendered
            .files
            .iter()
            .map(|file| file.relative_path.clone())
            .collect();

        Ok(ExportOutcome {
            export_path: report.mod_path,
            installed_path,
            mods_config_backup,
            skipped: render.skipped,
            files,
            decisions_sha256: render.decisions_sha256,
        })
    }

    /// Copies `rendered` into `mods_dir` and appends its package id to the
    /// **current** `ModsConfig.xml` order (not the selected one — install
    /// is not apply), if absent, when `options.install` is set. Returns
    /// `(None, None)` unconditionally otherwise. The foreign-folder check
    /// for `mods_dir` already ran in [`Self::execute`], before the first
    /// write — never repeated here.
    fn maybe_install(
        &self,
        session: &mut Session,
        id: &PatchId,
        options: &ExportOptions,
        mods_dir: &Path,
        rendered: &RenderedMod,
    ) -> Result<(Option<PathBuf>, Option<PathBuf>), ExportPatchError> {
        if !options.install {
            return Ok((None, None));
        }

        let install_backup_dir =
            export_folder::backup_dir(session, "patches", id.as_str(), "installed.prev");
        let package_id = session
            .patch(id)
            .unwrap_or_else(|| unreachable!("still loaded: only ever removed by DeletePatch"))
            .identity()
            .package_id()
            .clone();
        let outcome = export_folder::install(
            &self.writer,
            &self.config_store,
            session,
            mods_dir,
            &install_backup_dir,
            rendered,
            &package_id,
        )?;

        Ok((
            Some(outcome.installed_path),
            Some(outcome.mods_config_backup),
        ))
    }
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeSet;

    use rim_analyzer::analysis::SourceIndex;
    use rim_analyzer::domain::{GeneratedMarker, ModId, Report};
    use rim_resolve::domain::{Action, Decision, DefKey, OrderSource, PatchScope};

    use super::*;
    use crate::ProjectPaths;
    use crate::ports::ModsConfigFile;
    use crate::test_support::{
        FakeAssetLocator, InMemoryDefSourceReader, InMemoryMergeModWriter, InMemoryModsConfigStore,
        InMemoryPatchProjectStore, bionic_heart_fixture, bionic_heart_fixture_flat,
        patch_fixture_with_paths, patch_fixture_with_sources,
    };

    /// The identity [`patch_fixture_with_sources`] always builds
    /// (`new_test_patch_project`'s own fixed shape): package id
    /// `"test.patch"`, folder name `"test_patch"`.
    const TEST_PATCH_PACKAGE_ID: &str = "test.patch";
    const TEST_PATCH_FOLDER_NAME: &str = "test_patch";

    fn finding_key() -> FindingKey {
        FindingKey::DefOverride {
            key: DefKey {
                def_type: "HediffDef".to_string(),
                def_name: "BionicHeart".to_string(),
            },
            owners: [
                ModId::new("ludeon.rimworld"),
                ModId::new("example.bionicsfork"),
            ]
            .into_iter()
            .collect(),
        }
    }

    fn config_store() -> InMemoryModsConfigStore {
        InMemoryModsConfigStore::new(ModsConfigFile {
            version: "1.6".to_string(),
            active_mods: vec![
                ModId::new("ludeon.rimworld"),
                ModId::new("example.bionicsfork"),
            ],
            known_expansions: Vec::new(),
        })
    }

    #[allow(clippy::type_complexity)]
    fn use_case(
        writer: InMemoryMergeModWriter,
        config: InMemoryModsConfigStore,
        store: InMemoryPatchProjectStore,
        reader: InMemoryDefSourceReader,
    ) -> ExportPatch<
        InMemoryMergeModWriter,
        InMemoryDefSourceReader,
        FakeAssetLocator,
        InMemoryModsConfigStore,
        InMemoryPatchProjectStore,
    > {
        ExportPatch::new(writer, reader, FakeAssetLocator::default(), config, store)
    }

    /// Builds a session with one patch scoped to `ludeon.rimworld`/
    /// `example.bionicsfork` (the [`bionic_heart_fixture`] worked example's
    /// structural-guard-free twin, [`bionic_heart_fixture_flat`] — this
    /// module's own tests are about the export pipeline, never the guard;
    /// see that fixture's own doc comment for why `bionic_heart_fixture`
    /// itself would make every one of them fail with
    /// `ExportPatchError::NothingToExport`, since its real `ParentName`
    /// difference permanently guards it),
    /// with a `Merge` decision already recorded so there is something to
    /// export — plus the fixture's own seeded reader, which every export
    /// (rendering the def's real XML text back) needs to actually resolve
    /// the preview, unlike an empty [`InMemoryDefSourceReader::default`].
    fn decided_patch_fixture() -> (Session, PatchId, InMemoryDefSourceReader) {
        decided_patch_fixture_with(patch_fixture_with_sources)
    }

    /// [`decided_patch_fixture`], but with a session built by `build`
    /// instead of always [`patch_fixture_with_sources`] — for
    /// [`refuses_an_out_dir_inside_the_games_mods_folder`], the one test
    /// that needs [`crate::test_support::patch_fixture_with_paths`]'s own
    /// absolute `game_dir` instead of every other fixture's relative one.
    fn decided_patch_fixture_with(
        build: impl FnOnce(SourceIndex, Report, PatchScope) -> (Session, PatchId),
    ) -> (Session, PatchId, InMemoryDefSourceReader) {
        let fixture = bionic_heart_fixture_flat();
        let scope = PatchScope::new([
            ModId::new("ludeon.rimworld"),
            ModId::new("example.bionicsfork"),
        ])
        .expect("two distinct members");
        let (mut session, id) = build(fixture.sources, fixture.report, scope);
        session
            .patch_decide(
                &id,
                Decision {
                    key: finding_key(),
                    action: Action::Merge {
                        key: DefKey {
                            def_type: "HediffDef".to_string(),
                            def_name: "BionicHeart".to_string(),
                        },
                        choices: std::collections::BTreeMap::new(),
                    },
                    note: None,
                    decided_at: jiff::Timestamp::UNIX_EPOCH,
                },
            )
            .expect("the scope admits this finding");
        (session, id, fixture.reader)
    }

    /// Every fixture in this module's own `game_dir`/`profile_dir` are
    /// relative (`test_support::session_fixture`'s shared shape), so
    /// [`options`] roots its own `out_dir` well clear of both under a
    /// distinct, absolute base — satisfying
    /// [`ExportPatchError::OutDirNotAbsolute`] without ever colliding
    /// with a relative `game_dir`-derived `Mods` path.
    fn exports_base() -> &'static Path {
        Path::new("C:/exports")
    }

    fn options(out_dir: &str) -> ExportOptions {
        ExportOptions {
            out_dir: exports_base().join(out_dir),
            install: false,
        }
    }

    #[test]
    fn exports_a_complete_patch_and_persists_the_export_dir() {
        let (mut session, id, reader) = decided_patch_fixture();
        let store = InMemoryPatchProjectStore::new();
        let use_case = use_case(InMemoryMergeModWriter::new(), config_store(), store, reader);

        let outcome = use_case
            .execute(&mut session, &id, options("out"))
            .expect("export must succeed");

        assert_eq!(
            outcome.export_path,
            exports_base().join("out").join(TEST_PATCH_FOLDER_NAME)
        );
        assert!(outcome.installed_path.is_none());
        assert!(outcome.mods_config_backup.is_none());
        assert!(!outcome.files.is_empty());
        assert_eq!(
            use_case
                .store
                .last_saved(&id)
                .and_then(|project| project.export_dir().map(Path::to_path_buf)),
            Some(exports_base().join("out"))
        );
        assert_eq!(
            session
                .patch(&id)
                .expect("still loaded")
                .export_dir()
                .map(Path::to_path_buf),
            Some(exports_base().join("out"))
        );
    }

    #[test]
    fn refuses_a_relative_out_dir() {
        let (mut session, id, reader) = decided_patch_fixture();
        let use_case = use_case(
            InMemoryMergeModWriter::new(),
            config_store(),
            InMemoryPatchProjectStore::new(),
            reader,
        );

        let result = use_case.execute(
            &mut session,
            &id,
            ExportOptions {
                out_dir: PathBuf::from("Mods/x"),
                install: false,
            },
        );

        assert!(matches!(
            result,
            Err(ExportPatchError::OutDirNotAbsolute(_))
        ));
        assert!(use_case.writer.writes().is_empty());
    }

    #[test]
    fn refuses_when_nothing_is_ready_to_export() {
        let fixture = bionic_heart_fixture();
        let scope = PatchScope::new([
            ModId::new("ludeon.rimworld"),
            ModId::new("example.bionicsfork"),
        ])
        .expect("two distinct members");
        let (mut session, id) = patch_fixture_with_sources(fixture.sources, fixture.report, scope);
        let use_case = use_case(
            InMemoryMergeModWriter::new(),
            config_store(),
            InMemoryPatchProjectStore::new(),
            InMemoryDefSourceReader::default(),
        );

        let result = use_case.execute(&mut session, &id, options("out"));

        assert!(matches!(result, Err(ExportPatchError::NothingToExport)));
    }

    fn absolute_test_paths() -> ProjectPaths {
        ProjectPaths {
            game_dir: PathBuf::from("C:/game"),
            workshop_dir: PathBuf::from("C:/workshop"),
            mods_config: PathBuf::from("C:/game/ModsConfig.xml"),
            profile_dir: PathBuf::from("C:/profile"),
        }
    }

    #[test]
    fn refuses_an_out_dir_inside_the_games_mods_folder() {
        // Needs an *absolute* `game_dir` (unlike every other fixture's
        // relative `"game"`): `options.out_dir` must be absolute too
        // (`ExportPatchError::OutDirNotAbsolute`), and comparing an
        // absolute `out_dir` against a relative `Mods` path could never
        // exercise `is_inside`'s real comparison.
        let (mut session, id, reader) = decided_patch_fixture_with(|sources, report, scope| {
            patch_fixture_with_paths(sources, report, scope, absolute_test_paths())
        });
        let use_case = use_case(
            InMemoryMergeModWriter::new(),
            config_store(),
            InMemoryPatchProjectStore::new(),
            reader,
        );
        let mods_subfolder = session.paths().game_dir.join("Mods").join("some_folder");

        let result = use_case.execute(
            &mut session,
            &id,
            ExportOptions {
                out_dir: mods_subfolder,
                install: false,
            },
        );

        assert!(matches!(
            result,
            Err(ExportPatchError::OutDirIsModsFolder(_))
        ));
        assert!(use_case.writer.writes().is_empty());
    }

    #[test]
    fn refuses_to_overwrite_a_foreign_folder() {
        let (mut session, id, reader) = decided_patch_fixture();
        let writer = InMemoryMergeModWriter::new();
        // Seed a folder of the same (derived) name, marked as belonging to
        // a different patch id entirely.
        writer.set_marker(
            TEST_PATCH_FOLDER_NAME,
            GeneratedMarker {
                kind: GeneratedKind::Patch,
                patch_id: Some("abcdef012345".to_string()),
                scope: Some(BTreeSet::new()),
            },
        );
        let use_case = use_case(
            writer,
            config_store(),
            InMemoryPatchProjectStore::new(),
            reader,
        );

        let result = use_case.execute(&mut session, &id, options("out"));

        assert!(matches!(
            result,
            Err(ExportPatchError::ForeignFolder { .. })
        ));
    }

    /// Both foreign-folder checks, the install-side one included, run
    /// before the first write — a foreign `Mods/` folder must not leave
    /// `out_dir` written to or `export_dir` persisted when the whole export
    /// ultimately fails.
    #[test]
    fn a_foreign_mods_folder_on_install_leaves_the_export_dir_and_out_dir_untouched() {
        let (mut session, id, reader) = decided_patch_fixture();
        let writer = InMemoryMergeModWriter::new();
        let mods_dir = session.paths().game_dir.join("Mods");
        writer.set_marker_in(
            &mods_dir,
            TEST_PATCH_FOLDER_NAME,
            GeneratedMarker {
                kind: GeneratedKind::Patch,
                patch_id: Some("abcdef012345".to_string()),
                scope: Some(BTreeSet::new()),
            },
        );
        let store = InMemoryPatchProjectStore::new();
        let use_case = use_case(writer, config_store(), store, reader);

        let result = use_case.execute(
            &mut session,
            &id,
            ExportOptions {
                out_dir: exports_base().join("out"),
                install: true,
            },
        );

        assert!(matches!(
            result,
            Err(ExportPatchError::ForeignFolder { .. })
        ));
        assert!(
            use_case.writer.writes().is_empty(),
            "nothing must be written to out_dir once the install target is known foreign"
        );
        assert!(
            session
                .patch(&id)
                .expect("still loaded")
                .export_dir()
                .is_none(),
            "export_dir must never be persisted when install refuses"
        );
        assert!(use_case.store.last_saved(&id).is_none());
    }

    #[test]
    fn re_exporting_its_own_previous_folder_succeeds() {
        let (mut session, id, reader) = decided_patch_fixture();
        let store = InMemoryPatchProjectStore::new();
        let use_case = use_case(InMemoryMergeModWriter::new(), config_store(), store, reader);

        use_case
            .execute(&mut session, &id, options("out"))
            .expect("first export must succeed");
        let second = use_case.execute(&mut session, &id, options("out"));

        assert!(
            second.is_ok(),
            "the fake writer must recognize its own previous export's marker: {second:?}"
        );
        assert_eq!(use_case.writer.writes().len(), 2);
    }

    #[test]
    fn installing_copies_into_mods_and_appends_the_package_id() {
        let (mut session, id, reader) = decided_patch_fixture();
        let store = InMemoryPatchProjectStore::new();
        let use_case = use_case(InMemoryMergeModWriter::new(), config_store(), store, reader);

        let outcome = use_case
            .execute(
                &mut session,
                &id,
                ExportOptions {
                    out_dir: exports_base().join("out"),
                    install: true,
                },
            )
            .expect("export with install must succeed");

        let installed_path = outcome
            .installed_path
            .expect("install must produce an installed path");
        assert_eq!(
            installed_path,
            session
                .paths()
                .game_dir
                .join("Mods")
                .join(TEST_PATCH_FOLDER_NAME)
        );
        assert!(outcome.mods_config_backup.is_some());
        let writes = use_case.config_store.writes();
        assert_eq!(writes.len(), 1);
        assert!(
            writes[0]
                .active_mods
                .contains(&ModId::new(TEST_PATCH_PACKAGE_ID))
        );
    }

    /// `install`'s own append to `ModsConfig.xml` must update
    /// `session.orders().current` through [`Session::set_current_order`];
    /// otherwise a later `Apply { write_mods_config: true }` — with no
    /// reload in between, and `selected() == OrderSource::Current` (the
    /// default) — would read the *stale* in-memory order and write it
    /// straight back, silently dropping the package id `install` had just
    /// appended.
    #[test]
    fn installing_updates_current_order_so_a_later_apply_keeps_the_patch_active() {
        let (mut session, id, reader) = decided_patch_fixture();
        let use_case = use_case(
            InMemoryMergeModWriter::new(),
            config_store(),
            InMemoryPatchProjectStore::new(),
            reader,
        );

        use_case
            .execute(
                &mut session,
                &id,
                ExportOptions {
                    out_dir: exports_base().join("out"),
                    install: true,
                },
            )
            .expect("export with install must succeed");

        assert!(
            session
                .orders()
                .current
                .as_slice()
                .contains(&ModId::new(TEST_PATCH_PACKAGE_ID)),
            "install must update the session's own current order, not just the file on disk"
        );
        assert_eq!(session.selected(), OrderSource::Current);

        // A later apply, with no reload in between, must still see the
        // patch in the order it writes.
        let apply = crate::use_cases::Apply::new(
            config_store(),
            crate::test_support::InMemoryDecisionStore::new(),
            crate::test_support::InMemoryRuleStore::new(),
            InMemoryMergeModWriter::new(),
            InMemoryDefSourceReader::default(),
            FakeAssetLocator::default(),
        );

        apply
            .execute(
                &mut session,
                crate::use_cases::ApplyOptions {
                    source: rim_resolve::domain::OrderSource::Current,
                    write_mods_config: true,
                    write_merge_mod: false,
                },
            )
            .expect("apply must succeed");

        assert!(
            session
                .orders()
                .current
                .as_slice()
                .contains(&ModId::new(TEST_PATCH_PACKAGE_ID)),
            "apply must not have dropped the just-installed patch from current"
        );
    }

    #[test]
    fn without_install_the_config_store_is_never_written() {
        let (mut session, id, reader) = decided_patch_fixture();
        let use_case = use_case(
            InMemoryMergeModWriter::new(),
            config_store(),
            InMemoryPatchProjectStore::new(),
            reader,
        );

        use_case
            .execute(&mut session, &id, options("out"))
            .expect("export must succeed");

        assert!(use_case.config_store.writes().is_empty());
    }

    #[test]
    fn a_failed_save_rolls_back_the_export_dir_but_keeps_the_written_files() {
        let (mut session, id, reader) = decided_patch_fixture();
        let store = InMemoryPatchProjectStore::new();
        store.fail_next_save();
        let writer = InMemoryMergeModWriter::new();
        let use_case = use_case(writer, config_store(), store, reader);

        let result = use_case.execute(&mut session, &id, options("out"));

        assert!(matches!(result, Err(ExportPatchError::Store(_))));
        assert!(
            session
                .patch(&id)
                .expect("still loaded")
                .export_dir()
                .is_none(),
            "the export_dir mutation must be rolled back"
        );
        assert_eq!(
            use_case.writer.writes().len(),
            1,
            "the file write itself is never rolled back"
        );
    }

    #[test]
    fn rejects_an_unknown_patch() {
        let (mut session, _id, reader) = decided_patch_fixture();
        let use_case = use_case(
            InMemoryMergeModWriter::new(),
            config_store(),
            InMemoryPatchProjectStore::new(),
            reader,
        );
        let bogus: PatchId = "abcdef012345".parse().expect("valid id");

        let result = use_case.execute(&mut session, &bogus, options("out"));

        assert!(matches!(result, Err(ExportPatchError::Unknown(_))));
    }
}
