//! [`RenderMergeMod`]: ensures every `Merge` decision has a preview,
//! collects complete plans plus every located `ShipAsset` copy, and
//! renders the generated merge mod's files — the shared core behind both
//! `Apply` (which then writes the result) and the desktop `get_merge_mod`
//! command (which only wants to *describe* it, never writing anything).

use std::collections::{BTreeMap, BTreeSet};
use std::path::PathBuf;

use rim_analyzer::domain::ModId;
use rim_merge::emit::{
    self, AboutSpec, AssetCopy, Dependencies, EmitInput, Provenance, RenderedMod,
};
use rim_resolve::domain::{
    Action, DecisionSet, DefKey, FindingKey, GeneratedModIdentity, MergeState, PatchProject,
    ResolutionStatus,
};

use super::plan_merge::{MergeContext, PlanMerge, PlanMergeError, stored_choices};
use crate::Session;
use crate::merge_workspace::PreviewSlot;
use crate::ports::{AssetLocator, DefSourceError, DefSourceReader};

/// What [`RenderMergeMod::render`] renders: the profile's own merge mod
/// (every complete `Merge`/`ShipAsset` decision in [`Session::decisions`]),
/// or one compat patch's (only that project's own [`PatchProject::decisions`]).
/// `Copy` — it holds at most one shared reference — so `render` can match
/// on it more than once without threading a borrow through every branch.
#[derive(Debug, Clone, Copy)]
pub enum RenderTarget<'a> {
    /// The per-profile generated merge mod — [`RenderMergeMod::execute`]'s
    /// own target.
    Profile,
    /// One compat patch project's own export candidate.
    Patch(&'a PatchProject),
}

/// `target`'s own decision set: [`Session::decisions`] for the profile,
/// `project.decisions()` for a patch. The one place this module still
/// reaches for `session.decisions()` — every other function here works
/// from this borrow (or from [`MergeContext::choices`]) instead of asking
/// `session` for it again.
fn decisions_for<'a>(session: &'a Session, target: RenderTarget<'a>) -> &'a DecisionSet {
    match target {
        RenderTarget::Profile => session.decisions(),
        RenderTarget::Patch(project) => project.decisions(),
    }
}

/// This build's own version string, embedded in the generated
/// `rimmerge.json` (see [`EmitInput::rimmerge_version`]) — `rim-session`'s
/// own crate version, the closest thing this workspace has to a shared
/// "app version" constant at the point this use case runs.
pub(crate) const RIMMERGE_VERSION: &str = env!("CARGO_PKG_VERSION");

/// The profile merge mod's fixed `<author>` — unlike a compat patch's, this
/// is never user-editable.
const PROFILE_AUTHOR: &str = "Rimmerge";

/// The profile merge mod's fixed `<description>` (only the compat patch
/// export gets a user-editable one).
const PROFILE_DESCRIPTION: &str = "Generated by Rimmerge from your merge decisions. Regenerated on every apply — do not edit by hand.";

/// The game major.minor version [`EmitInput::game_version`] wants, taken
/// from the full version string the scan recorded (e.g. `"1.6.4525 rev123"`
/// -> `"1.6"`). `pub(crate)`: [`super::export_assignment::ExportAssignment`]
/// needs the identical conversion for its own `EmitInput`.
pub(crate) fn major_minor(game_version: &str) -> String {
    let mut parts = game_version.split(|c: char| !c.is_ascii_digit() && c != '.');
    parts
        .next()
        .unwrap_or(game_version)
        .splitn(3, '.')
        .take(2)
        .collect::<Vec<_>>()
        .join(".")
}

fn asset_relative_target(texture_path: &str, source: &std::path::Path) -> PathBuf {
    let ext = source.extension().and_then(|e| e.to_str()).unwrap_or("png");
    PathBuf::from(format!("{texture_path}.{ext}"))
}

/// Everything that can go wrong rendering the merge mod.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum RenderMergeModError {
    /// Building a merge preview (for a decision with no cached one yet)
    /// failed.
    #[error("planning a merge: {0}")]
    Plan(#[from] PlanMergeError),
    /// Locating a `ShipAsset` texture's source file failed.
    #[error("locating an asset: {0}")]
    Asset(DefSourceError),
    /// Rendering the merge mod's files failed.
    #[error("rendering the merge mod: {0}")]
    Emit(#[from] emit::EmitError),
}

/// What kind of finding [`MergeModEntry::key`] names.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MergeEntryKind {
    /// An `Action::Merge` decision on a `FindingKey::DefOverride`.
    DefOverride,
    /// An `Action::Merge` decision on a `FindingKey::PatchCollision`.
    PatchCollision,
    /// An `Action::ShipAsset` decision, located or not.
    Asset,
}

/// One `Merge`/`ShipAsset` decision's contribution to the generated merge
/// mod, whether or not it actually rendered anything.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MergeModEntry {
    /// The finding this entry describes.
    pub key: FindingKey,
    /// The contested def, for a `DefOverride`/`PatchCollision` entry.
    /// `None` for an `Asset` entry (a texture has no def key).
    pub def_key: Option<DefKey>,
    /// What kind of finding [`Self::key`] is.
    pub kind: MergeEntryKind,
    /// The merge preview's status at render time (a real
    /// [`MergeState::Complete`] for a located asset, standing in for "the
    /// one texture copy is ready" — assets have no field-level diff of
    /// their own to report a state for; an asset whose mod or texture
    /// can't be found gets [`MergeState::CannotMerge`] instead, naming
    /// why).
    pub state: MergeState,
    /// How many ops this entry contributed (the texture copy counts as
    /// one for a located `Asset` entry, zero for one that couldn't be).
    pub op_count: usize,
    /// The mods whose values this entry's ops carry — the union of every
    /// contributing [`rim_merge::plan::PlannedOp::depends_on`], or just
    /// the asset's own `from` for an `Asset` entry.
    pub depends_on: BTreeSet<ModId>,
    /// The `Patches/rimmerge_<DefType>.xml` this entry's ops land in.
    /// `None` for an `Asset` entry, and for a `DefOverride`/
    /// `PatchCollision` entry whose plan has no ops at all (nothing was
    /// actually written to any file on its behalf, even though the file
    /// may still exist because of some *other* def's ops).
    pub patch_file: Option<PathBuf>,
    /// The structural guard ([`crate::MergePreview::structural_guard_field`]): the field that
    /// forced this entry's [`MergeState::NeedsFieldInput`], if any. Always
    /// `None` for a `PatchCollision`/`Asset` entry (the guard is
    /// `DefOverride`-only) and for a `DefOverride` entry the guard never
    /// fired for. The desktop apply dialog uses this to tell a
    /// structurally-guarded skip ("not auto-merged — confirm the winner")
    /// apart from a genuine needs-input one ("still needs input").
    pub structural_guard_field: Option<String>,
}

/// What [`RenderMergeMod::execute`] produced.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MergeModRender {
    /// The generated mod's derived identity — computed here so callers
    /// (the desktop `get_merge_mod`/`preview_merge_mod_file` commands)
    /// never have to re-derive it themselves.
    pub identity: GeneratedModIdentity,
    /// The generated mod's full path under the game's `Mods/` folder.
    pub mods_path: PathBuf,
    /// The rendered mod, or `None` when there was nothing to render (no
    /// complete merge and no located asset).
    pub rendered: Option<RenderedMod>,
    /// `Merge`/`ShipAsset` decisions skipped because their preview wasn't
    /// [`MergeState::Complete`] (a `Merge` needing more field input or
    /// unable to merge at all), or because the `ShipAsset`'s mod or
    /// texture couldn't be found.
    pub skipped: Vec<FindingKey>,
    /// One entry per `Merge` decision (skipped ones included) and per
    /// `ShipAsset` decision (located or not).
    pub entries: Vec<MergeModEntry>,
    /// The canonical hash of the decisions this render was built from —
    /// [`rim_resolve::domain::DecisionSet::content_sha256`] over
    /// [`Session::decisions`] for the profile,
    /// [`PatchProject::decisions_sha256`] for a patch (itself a thin
    /// wrapper over the same method) — both kinds of generated mod's
    /// `rimmerge.json` carry a hash built the same canonical way. Always
    /// populated, even when [`Self::rendered`] is `None`.
    pub decisions_sha256: String,
    /// Exactly what [`Self::rendered`]'s `About.xml` declares as
    /// `modDependencies`/`loadAfter`, so a caller (the desktop DTO layer)
    /// never has to re-derive it from [`Self::entries`]: the union of
    /// every rendered entry's `depends_on` for the profile
    /// (`Dependencies::FromContent`), or exactly the patch's own scope
    /// (`Dependencies::Exactly`) — which may include a member no op
    /// touches. Empty when nothing rendered.
    pub dependencies: BTreeSet<ModId>,
}

fn entry_kind(key: &FindingKey) -> MergeEntryKind {
    match key {
        FindingKey::DefOverride { .. } => MergeEntryKind::DefOverride,
        FindingKey::PatchCollision { .. } => MergeEntryKind::PatchCollision,
        // `PlanMerge::execute` only ever accepts these two shapes for a
        // `Merge` decision (`PlanMergeError::UnsupportedFinding`
        // otherwise), so by the time a preview exists to build an entry
        // from, the key can't be anything else.
        other => unreachable!("a Merge decision's key must be mergeable: {other:?}"),
    }
}

/// A [`MergeModEntry`] for a `ShipAsset` decision whose mod or texture
/// couldn't be found: [`MergeState::CannotMerge`] naming `reason`, no ops,
/// no patch file.
fn cannot_merge_asset_entry(key: FindingKey, from: &ModId, reason: String) -> MergeModEntry {
    MergeModEntry {
        key,
        def_key: None,
        kind: MergeEntryKind::Asset,
        state: MergeState::CannotMerge { reason },
        op_count: 0,
        depends_on: BTreeSet::from([from.clone()]),
        patch_file: None,
        structural_guard_field: None,
    }
}

/// Whether an auto-suggested (undecided) `Merge` entry's own cached
/// preview state says its plan is empty — writing it would produce
/// nothing. `rim_resolve::domain::redecide_for_clean_merge` already
/// refuses to promote a zero-op preview to `Action::Merge` in the first
/// place (see that
/// function's own doc comment), so `entry.effective` being `Merge` with
/// no decision should already imply `op_count > 0`; this is an
/// independent, explicit check kept here anyway rather than trusted
/// transitively, so this use case's own "never write an empty merge for
/// an undecided finding" invariant holds regardless of what the ledger's
/// own promotion rule does. An *explicitly decided* zero-op merge is
/// never checked against this at all (see [`RenderMergeMod::execute`]'s
/// own `merge_keys` construction: a decided key is collected before this
/// filter ever runs) — it must still render.
fn is_zero_op_complete(state: &Option<MergeState>) -> bool {
    matches!(state, Some(MergeState::Complete { op_count: 0 }))
}

fn def_key_of(key: &FindingKey) -> DefKey {
    match key {
        FindingKey::DefOverride { key: def_key, .. }
        | FindingKey::PatchCollision { key: def_key, .. } => def_key.clone(),
        other => unreachable!("a Merge decision's key must be mergeable: {other:?}"),
    }
}

/// Ensures every `Merge` decision has a preview (computing missing ones),
/// collects [`MergeState::Complete`] plans plus every `ShipAsset` copy,
/// and renders the generated merge mod's files.
pub struct RenderMergeMod<Reader, Assets> {
    planner: PlanMerge<Reader>,
    asset_locator: Assets,
}

impl<Reader: DefSourceReader, Assets: AssetLocator> RenderMergeMod<Reader, Assets> {
    /// Builds the use case from its ports.
    #[must_use]
    pub fn new(reader: Reader, asset_locator: Assets) -> Self {
        Self {
            planner: PlanMerge::new(reader),
            asset_locator,
        }
    }

    /// [`Self::render`] against [`RenderTarget::Profile`] — every
    /// profile caller (`Apply`, the desktop `get_merge_mod`/
    /// `preview_merge_mod_file` commands) goes through here.
    ///
    /// # Errors
    ///
    /// See [`RenderMergeModError`].
    pub fn execute(&self, session: &mut Session) -> Result<MergeModRender, RenderMergeModError> {
        self.render(session, RenderTarget::Profile)
    }

    /// Ensures every `Merge` decision in `target`'s own decision set has a
    /// preview (computing missing ones), collects
    /// [`MergeState::Complete`] plans plus every located `ShipAsset`
    /// copy, and renders `target`'s generated mod files.
    ///
    /// # Errors
    ///
    /// See [`RenderMergeModError`].
    pub fn render(
        &self,
        session: &mut Session,
        target: RenderTarget<'_>,
    ) -> Result<MergeModRender, RenderMergeModError> {
        let profile_hash = session.paths().profile_hash().to_string();
        let source = session.selected();
        let (identity, slot) = match target {
            RenderTarget::Profile => (
                GeneratedModIdentity::for_profile(&profile_hash),
                PreviewSlot::profile(source),
            ),
            RenderTarget::Patch(project) => (
                project.identity().as_generated(),
                PreviewSlot::patch(source, project.id().clone()),
            ),
        };
        let mods_path = session
            .paths()
            .game_dir
            .join("Mods")
            .join(&identity.folder_name);
        // A patch render must plan under the same scoped participant rule
        // `DecidePatchMerge` used
        // to validate the stored choices in the first place — otherwise a
        // choice naming one of the restricted diff's candidates could land
        // against a differently-shaped (unrestricted) diff here.
        let scope = match target {
            RenderTarget::Profile => None,
            RenderTarget::Patch(project) => Some(project.scope().clone()),
        };

        let mut merge_keys: Vec<FindingKey> = decisions_for(session, target)
            .iter()
            .filter(|decision| matches!(decision.action, Action::Merge { .. }))
            .map(|decision| decision.key.clone())
            .collect();
        // A finding with no decision
        // at all still lands in the profile's merge mod once its ledger
        // suggestion has auto-accepted `Merge` (confidence 85 at the
        // default threshold — see
        // `rim_resolve::domain::redecide_for_clean_merge`), exactly as if
        // the user had decided it explicitly — but **only for a
        // `PatchCollision`**, where the merge mirrors RimWorld's own
        // sequential composition of every active mod's own patch. A
        // `DefOverride` enters the merge mod only by an *explicit*
        // `Action::Merge` decision (collected into `merge_keys` above,
        // unaffected by this filter): a field-merged def override is a
        // def copy no author ever shipped — RimWorld itself takes the
        // last owner's copy wholesale — so writing one into the generated
        // mod without the user having asked for it is a different, and
        // much stronger, claim than "the game already does this". A
        // patch's own scoped ledger (`Session::patch_ledger`) deliberately
        // never runs this auto-promotion — its inbox shows exactly
        // what's decided or the scope's own rewritten suggestion, never an
        // auto-applied merge — so only its own explicit decisions render
        // here.
        //
        // `Session::redecide_clean_merge_at` is otherwise only run lazily
        // per displayed finding (`Session::resolution`) — too slow to run
        // for every finding on every ledger build (see that method's own
        // doc comment) — so apply is the one place that pays the full
        // cost eagerly, over every candidate, since it's a deliberate,
        // occasional action rather than part of the inbox's hot path.
        if matches!(target, RenderTarget::Profile) {
            let all_keys: Vec<FindingKey> = session
                .ledger(source)
                .entries
                .iter()
                .map(|entry| entry.key.clone())
                .collect();
            session.prefetch_clean_merge_previews(source);
            for key in &all_keys {
                session.redecide_clean_merge_at(source, key);
            }
            merge_keys.extend(
                session
                    .ledger(source)
                    .entries
                    .iter()
                    .filter(|entry| {
                        entry.decision.is_none()
                            && entry.status == ResolutionStatus::Auto
                            && matches!(entry.effective, Action::Merge { .. })
                            && matches!(entry.key, FindingKey::PatchCollision { .. })
                            && !is_zero_op_complete(&entry.merge)
                    })
                    .map(|entry| entry.key.clone()),
            );
        }

        let mut plans = Vec::new();
        let mut skipped = Vec::new();
        let mut entries = Vec::new();

        for key in &merge_keys {
            if session.merge_preview(&slot, key).is_none() {
                let choices = stored_choices(decisions_for(session, target), key);
                let ctx = MergeContext {
                    slot: slot.clone(),
                    choices,
                    scope: scope.clone(),
                };
                self.planner.execute_in(session, ctx, key)?;
            }
            let preview = session
                .merge_preview(&slot, key)
                .unwrap_or_else(|| unreachable!("just ensured a preview above"));

            let op_count = preview.plan.ops.len();
            let depends_on: BTreeSet<ModId> = preview
                .plan
                .ops
                .iter()
                .flat_map(|op| op.depends_on.iter().cloned())
                .collect();
            let patch_file =
                (op_count > 0).then(|| emit::patch_file_path(&preview.plan.key.def_type));

            entries.push(MergeModEntry {
                key: key.clone(),
                def_key: Some(def_key_of(key)),
                kind: entry_kind(key),
                state: preview.state.clone(),
                op_count,
                depends_on,
                patch_file,
                structural_guard_field: preview.structural_guard_field(),
            });

            match &preview.state {
                MergeState::Complete { .. } => plans.push(preview.plan.clone()),
                MergeState::NeedsFieldInput { .. } | MergeState::CannotMerge { .. } => {
                    skipped.push(key.clone());
                }
            }
        }

        let mut assets = Vec::new();
        for decision in decisions_for(session, target).iter() {
            let Action::ShipAsset { texture_path, from } = &decision.action else {
                continue;
            };
            let Some(mod_entry) = session.report().mods.iter().find(|m| &m.id == from) else {
                entries.push(cannot_merge_asset_entry(
                    decision.key.clone(),
                    from,
                    format!("{from} is not an active mod"),
                ));
                skipped.push(decision.key.clone());
                continue;
            };
            let located = self
                .asset_locator
                .locate_texture(&mod_entry.loaded_folders, texture_path)
                .map_err(RenderMergeModError::Asset)?;
            let Some(source_path) = located else {
                entries.push(cannot_merge_asset_entry(
                    decision.key.clone(),
                    from,
                    format!("{texture_path} was not found among {from}'s files"),
                ));
                skipped.push(decision.key.clone());
                continue;
            };

            let relative_target = asset_relative_target(texture_path, &source_path);
            entries.push(MergeModEntry {
                key: decision.key.clone(),
                def_key: None,
                kind: MergeEntryKind::Asset,
                // An asset has no field-level diff to derive a state
                // from; "one op" (the texture copy) reads as `Complete`
                // the same way a def override with one resolved field
                // would.
                state: MergeState::Complete { op_count: 1 },
                op_count: 1,
                depends_on: BTreeSet::from([from.clone()]),
                patch_file: None,
                structural_guard_field: None,
            });
            assets.push(AssetCopy {
                texture_path: texture_path.clone(),
                from: from.clone(),
                source: source_path,
                relative_target,
            });
        }

        let dependencies: BTreeSet<ModId> = match target {
            // The profile behaviour: exactly the mods the rendered content
            // actually came from.
            RenderTarget::Profile => entries
                .iter()
                .filter(|entry| matches!(entry.state, MergeState::Complete { .. }))
                .flat_map(|entry| entry.depends_on.iter().cloned())
                .collect(),
            // `Dependencies::Exactly` below always declares precisely the
            // scope, even a member no op touches — mirror that here too.
            RenderTarget::Patch(project) => project.scope().members().clone(),
        };
        let decisions_sha256 = match target {
            RenderTarget::Profile => decisions_for(session, target).content_sha256(),
            RenderTarget::Patch(project) => project.decisions_sha256(),
        };

        if plans.is_empty() && assets.is_empty() {
            return Ok(MergeModRender {
                identity,
                mods_path,
                rendered: None,
                skipped,
                entries,
                decisions_sha256,
                dependencies,
            });
        }

        let mod_names: BTreeMap<ModId, String> = session
            .report()
            .mods
            .iter()
            .map(|m| (m.id.clone(), m.name.clone()))
            .collect();
        let game_version = major_minor(&session.report().metadata.game_version);
        let generated_at = jiff::Timestamp::now().to_string();

        let (about, provenance) = match target {
            RenderTarget::Profile => (
                AboutSpec {
                    identity: &identity,
                    author: PROFILE_AUTHOR,
                    description: PROFILE_DESCRIPTION,
                    dependencies: Dependencies::FromContent,
                },
                Provenance::ProfileMerge {
                    generated_at: &generated_at,
                    profile_hash: &profile_hash,
                    decisions_sha256: &decisions_sha256,
                },
            ),
            RenderTarget::Patch(project) => (
                AboutSpec {
                    identity: &identity,
                    author: project.author(),
                    description: project.description(),
                    dependencies: Dependencies::Exactly(project.scope().members()),
                },
                Provenance::CompatPatch {
                    patch_id: project.id().as_str(),
                    profile_hash: &profile_hash,
                    scope: project.scope().members(),
                    decisions_sha256: &decisions_sha256,
                },
            ),
        };

        let input = EmitInput {
            about,
            game_version: &game_version,
            plans: &plans,
            // Assignment projects render their own `Defs/` files through a
            // separate use case (`ExportAssignment`); neither a profile
            // merge nor a compat patch ever has any. See
            // `rim_merge::emit::EmitInput::defs`'s own doc comment.
            defs: &[],
            assets: &assets,
            mod_names: &mod_names,
            provenance,
            rimmerge_version: RIMMERGE_VERSION,
        };
        let rendered = emit::render(&input)?;
        Ok(MergeModRender {
            identity,
            mods_path,
            rendered: Some(rendered),
            skipped,
            entries,
            decisions_sha256,
            dependencies,
        })
    }
}

#[cfg(test)]
mod tests {
    use rim_analyzer::domain::Selector;
    use rim_merge::plan::MergePlan;
    use rim_resolve::domain::{Decision, MergeChoice, OrderSource, PatchModIdentity, PatchScope};

    use super::*;
    use crate::test_support::{
        FakeAssetLocator, InMemoryDefSourceReader, bionic_heart_fixture, bionic_heart_fixture_flat,
        bionic_heart_fixture_with_conflict, session_with_sources,
        whole_def_patch_collision_fixture,
    };

    fn bionic_heart_key() -> FindingKey {
        FindingKey::DefOverride {
            key: DefKey {
                def_type: "HediffDef".to_string(),
                def_name: "BionicHeart".to_string(),
            },
            owners: [
                ModId::new("ludeon.rimworld"),
                ModId::new("example.bionicsfork"),
            ]
            .into_iter()
            .collect(),
        }
    }

    fn decide_merge(session: &mut Session, key: FindingKey, def_key: DefKey) {
        session
            .decide(Decision {
                key,
                action: Action::Merge {
                    key: def_key,
                    choices: BTreeMap::new(),
                },
                note: None,
                decided_at: jiff::Timestamp::UNIX_EPOCH,
            })
            .unwrap_or_else(|error| unreachable!("Action::Merge always validates: {error:?}"));
    }

    #[test]
    fn nothing_renders_when_no_decision_exists() {
        let fixture = bionic_heart_fixture();
        let mut session = session_with_sources(fixture.sources, fixture.report);
        let use_case = RenderMergeMod::new(fixture.reader, FakeAssetLocator::default());

        let render = use_case
            .execute(&mut session)
            .expect("rendering must succeed");

        assert!(render.rendered.is_none());
        assert!(render.entries.is_empty());
        assert!(render.skipped.is_empty());
    }

    #[test]
    fn a_complete_merge_produces_an_entry_and_renders() {
        // `bionic_heart_fixture_flat`, not `bionic_heart_fixture`: this
        // test is about the render pipeline, not the structural guard —
        // see the flat fixture's own doc comment (`bionic_heart_fixture`
        // is permanently `NeedsFieldInput`, so it can never demonstrate a
        // complete, rendering merge at all).
        let fixture = bionic_heart_fixture_flat();
        let mut session = session_with_sources(fixture.sources, fixture.report);
        let def_key = DefKey {
            def_type: "HediffDef".to_string(),
            def_name: "BionicHeart".to_string(),
        };
        decide_merge(&mut session, bionic_heart_key(), def_key.clone());
        let use_case = RenderMergeMod::new(fixture.reader, FakeAssetLocator::default());

        let render = use_case
            .execute(&mut session)
            .expect("rendering must succeed");

        assert!(render.rendered.is_some());
        assert!(render.skipped.is_empty());
        assert_eq!(render.entries.len(), 1);
        let entry = &render.entries[0];
        assert_eq!(entry.key, bionic_heart_key());
        assert_eq!(entry.def_key, Some(def_key));
        assert!(matches!(entry.kind, MergeEntryKind::DefOverride));
        assert!(matches!(entry.state, MergeState::Complete { op_count: 0 }));
        assert_eq!(entry.op_count, 0);
        // A no-op plan (every field already resolves to the winner's own
        // value) contributes nothing to any patch file.
        assert!(entry.patch_file.is_none());
        assert_eq!(
            entry.structural_guard_field, None,
            "the flat fixture has no ParentName difference, so the structural guard never fires"
        );
    }

    /// A *pre-existing* `Action::Merge` decision on a def that becomes
    /// structurally guarded (BIONICS's own `ParentName` genuinely differs
    /// from Core's, the real `bionic_heart_fixture`) is not a silent
    /// no-op by accident — this pins that the behaviour is *deliberate*:
    /// the decision's own content silently leaves the generated merge mod
    /// (`RenderMergeMod` only ever renders a `Complete` preview), and the
    /// ledger stops presenting it as a finished decision
    /// (`Session::apply_merge_states`/`merge_status` flips
    /// `UserOverridden` to `NeedsInput` the moment the def's own cached
    /// preview is `NeedsFieldInput`, and tallies it under
    /// `LedgerStats::merge_incomplete`, never `merged`).
    #[test]
    fn a_pre_existing_merge_decision_on_a_now_guarded_def_is_flagged_needs_input_and_dropped() {
        // `_with_conflict`: a plain `bionic_heart_fixture` has no
        // `Conflict::DefOverride` on its report at all (its own tests
        // decide the merge directly, bypassing ledger extraction), so
        // the ledger this test reads would have no entry for the key
        // regardless of the decision.
        let fixture = bionic_heart_fixture_with_conflict();
        let mut session = session_with_sources(fixture.sources, fixture.report);
        let key = bionic_heart_key();
        let def_key = DefKey {
            def_type: "HediffDef".to_string(),
            def_name: "BionicHeart".to_string(),
        };
        decide_merge(&mut session, key.clone(), def_key);

        // Warm the preview cache *before* the ledger is ever built, so
        // the very first build already sees the guarded
        // (`NeedsFieldInput`) preview `apply_merge_states` reads —
        // mirrors a decision made while the def's preview was still
        // complete, re-opened once the guard applies.
        PlanMerge::new(fixture.reader.clone())
            .execute(&mut session, &key)
            .expect("planning a guarded def still succeeds");

        let ledger = session.ledger(OrderSource::Current);
        let entry = ledger
            .entries
            .iter()
            .find(|entry| entry.key == key)
            .expect("the decided finding must be in the ledger");
        assert_eq!(
            entry.status,
            ResolutionStatus::NeedsInput,
            "a Merge decision on a now-guarded def must not read as UserOverridden: {entry:?}"
        );
        assert_eq!(ledger.stats.merge_incomplete, 1, "{:?}", ledger.stats);
        assert_eq!(ledger.stats.merged, 0);

        // And its content never reaches the generated mod.
        let use_case = RenderMergeMod::new(fixture.reader, FakeAssetLocator::default());
        let render = use_case
            .execute(&mut session)
            .expect("rendering must succeed even with a guarded decided merge");
        assert!(render.rendered.is_none());
        assert_eq!(render.skipped, vec![key.clone()]);
        let entry = render
            .entries
            .iter()
            .find(|entry| entry.key == key)
            .expect("the guarded decision still gets an entry");
        assert_eq!(
            entry.structural_guard_field.as_deref(),
            Some("ParentName"),
            "the real bionic_heart_fixture's own ParentName difference must be surfaced \
             so the desktop apply dialog can tell this apart from a genuine needs-input skip"
        );
    }

    #[test]
    fn profile_decisions_sha256_matches_the_sessions_own_canonical_hash() {
        let fixture = bionic_heart_fixture();
        let mut session = session_with_sources(fixture.sources, fixture.report);
        let def_key = DefKey {
            def_type: "HediffDef".to_string(),
            def_name: "BionicHeart".to_string(),
        };
        decide_merge(&mut session, bionic_heart_key(), def_key);
        let use_case = RenderMergeMod::new(fixture.reader, FakeAssetLocator::default());

        let render = use_case
            .execute(&mut session)
            .expect("rendering must succeed");

        assert_eq!(
            render.decisions_sha256,
            session.decisions().content_sha256()
        );
    }

    /// A `NeedsFieldInput` preview is seeded directly through
    /// `Session::cache_merge_preview` (`pub(crate)`, reachable from this
    /// module) rather than through a real conflicting diff: the fixture's
    /// only two owners can never classify a field as `Conflict` (that
    /// needs 3+ differing candidates — see `crate::use_cases::plan_merge`'s
    /// own `classify`), so this is the direct way to exercise the "skip
    /// an incomplete merge" branch without inventing a third mod's XML.
    #[test]
    fn a_needs_field_input_merge_is_skipped_not_rendered() {
        let fixture = bionic_heart_fixture();
        let mut session = session_with_sources(fixture.sources, fixture.report);
        let def_key = DefKey {
            def_type: "HediffDef".to_string(),
            def_name: "BionicHeart".to_string(),
        };
        let key = bionic_heart_key();
        decide_merge(&mut session, key.clone(), def_key.clone());

        let winner = ModId::new("example.bionicsfork");
        let unresolved_path: rim_merge::tree::FieldPath = "label".parse().unwrap();
        session.cache_merge_preview(
            MergeContext {
                slot: crate::PreviewSlot::profile(OrderSource::Current),
                choices: BTreeMap::new(),
                scope: None,
            },
            crate::MergePreview {
                key: key.clone(),
                owners: vec![ModId::new("ludeon.rimworld"), winner.clone()],
                base: ModId::new("ludeon.rimworld"),
                winner: winner.clone(),
                diff: rim_merge::diff::ThreeWayDiff {
                    base: ModId::new("ludeon.rimworld"),
                    fields: Vec::new(),
                },
                plan: MergePlan {
                    key: def_key.clone(),
                    selector: Selector::DefName,
                    winner,
                    owners: vec![
                        ModId::new("ludeon.rimworld"),
                        ModId::new("example.bionicsfork"),
                    ],
                    ops: Vec::new(),
                    unresolved: vec![unresolved_path],
                    caveats: Vec::new(),
                },
                state: MergeState::NeedsFieldInput {
                    unresolved: 1,
                    total: 5,
                },
                structural_change: None,
                final_values: BTreeMap::new(),
            },
        );
        let use_case = RenderMergeMod::new(fixture.reader, FakeAssetLocator::default());

        let render = use_case
            .execute(&mut session)
            .expect("rendering must succeed even with a skipped merge");

        assert!(render.rendered.is_none(), "no complete plan and no asset");
        assert_eq!(render.skipped, vec![key.clone()]);
        assert_eq!(render.entries.len(), 1);
        assert!(matches!(
            render.entries[0].state,
            MergeState::NeedsFieldInput { .. }
        ));
        assert!(render.entries[0].patch_file.is_none());
    }

    #[test]
    fn a_located_asset_produces_an_entry_and_renders() {
        let fixture = bionic_heart_fixture();
        let mut session = session_with_sources(fixture.sources, fixture.report);
        let key = FindingKey::TextureOverride {
            texture_path: "Things/Foo".to_string(),
            owners: [
                ModId::new("ludeon.rimworld"),
                ModId::new("example.bionicsfork"),
            ]
            .into_iter()
            .collect(),
        };
        session
            .decide(Decision {
                key: key.clone(),
                action: Action::ShipAsset {
                    texture_path: "Things/Foo".to_string(),
                    from: ModId::new("ludeon.rimworld"),
                },
                note: None,
                decided_at: jiff::Timestamp::UNIX_EPOCH,
            })
            .unwrap_or_else(|error| unreachable!("Action::ShipAsset always validates: {error:?}"));
        let locator = FakeAssetLocator::new(BTreeMap::from([(
            "Things/Foo".to_string(),
            PathBuf::from("Textures/Things/Foo.png"),
        )]));
        let use_case = RenderMergeMod::new(InMemoryDefSourceReader::default(), locator);

        let render = use_case
            .execute(&mut session)
            .expect("rendering must succeed");

        assert!(render.rendered.is_some());
        assert_eq!(render.entries.len(), 1);
        let entry = &render.entries[0];
        assert_eq!(entry.key, key);
        assert!(entry.def_key.is_none());
        assert!(matches!(entry.kind, MergeEntryKind::Asset));
        assert!(matches!(entry.state, MergeState::Complete { op_count: 1 }));
        assert!(entry.patch_file.is_none());
    }

    #[test]
    fn an_asset_whose_texture_cannot_be_located_is_reported_cannot_merge_not_dropped() {
        let fixture = bionic_heart_fixture();
        let mut session = session_with_sources(fixture.sources, fixture.report);
        let key = FindingKey::TextureOverride {
            texture_path: "Things/Foo".to_string(),
            owners: [
                ModId::new("ludeon.rimworld"),
                ModId::new("example.bionicsfork"),
            ]
            .into_iter()
            .collect(),
        };
        session
            .decide(Decision {
                key: key.clone(),
                action: Action::ShipAsset {
                    texture_path: "Things/Foo".to_string(),
                    from: ModId::new("ludeon.rimworld"),
                },
                note: None,
                decided_at: jiff::Timestamp::UNIX_EPOCH,
            })
            .unwrap_or_else(|error| unreachable!("Action::ShipAsset always validates: {error:?}"));
        // No entries in this locator, so the texture is never found.
        let use_case = RenderMergeMod::new(
            InMemoryDefSourceReader::default(),
            FakeAssetLocator::default(),
        );

        let render = use_case
            .execute(&mut session)
            .expect("rendering must succeed even with an unlocatable asset");

        assert!(
            render.rendered.is_none(),
            "no complete plan and no located asset"
        );
        assert_eq!(render.skipped, vec![key.clone()]);
        assert_eq!(render.entries.len(), 1);
        let entry = &render.entries[0];
        assert_eq!(entry.key, key);
        assert!(matches!(entry.kind, MergeEntryKind::Asset));
        assert!(matches!(entry.state, MergeState::CannotMerge { .. }));
        assert_eq!(entry.op_count, 0);
        assert!(entry.patch_file.is_none());
    }

    /// A clean def
    /// override whose preview is `MergeState::Complete { op_count: 0 }`
    /// (every field already resolves to the load-order winner's own
    /// value — `bionic_heart_fixture_with_conflict`'s own shape) must
    /// never render just because `suggestMergeWhenClean` is on: nothing
    /// would actually be written, so the generated mod must stay exactly
    /// as if no merge had been suggested for it.
    #[test]
    fn a_zero_op_clean_override_with_no_decision_is_not_rendered_when_the_setting_is_on() {
        let fixture = bionic_heart_fixture_with_conflict();
        let mut session = session_with_sources(fixture.sources, fixture.report);
        session.set_def_source_reader(std::sync::Arc::new(fixture.reader.clone()));
        assert!(
            session.settings().suggest_merge_when_clean,
            "sanity check: the setting defaults on"
        );

        let use_case = RenderMergeMod::new(fixture.reader, FakeAssetLocator::default());
        let render = use_case
            .execute(&mut session)
            .expect("rendering must succeed even with nothing to render");

        assert!(
            render.rendered.is_none(),
            "a zero-op auto-suggested merge must never render"
        );
        assert!(render.entries.is_empty());
    }

    /// An undecided, auto-suggested
    /// `Merge` on a `DefOverride` does not enter the generated merge
    /// mod, *even* when its preview is a genuine, non-empty clean merge
    /// (`op_count > 0` — see [`crate::test_support::clean_override_fixture`]'s
    /// own doc comment for why a fixture needs a field the winner never
    /// touches to produce one). This is deliberate: a field-merged def
    /// override is a def copy no author ever shipped, unlike a
    /// `PatchCollision`'s merge, which only ever mirrors patches every
    /// active mod already runs itself.
    #[test]
    fn an_undecided_merge_on_a_clean_def_override_is_excluded_from_the_merge_mod() {
        let fixture =
            crate::test_support::clean_override_fixture("Wall", "contributor.mod", "winner.mod");
        let mut session = crate::test_support::session_with_sources_and_mods(
            fixture.sources,
            fixture.report,
            &["core.mod", "contributor.mod", "winner.mod"],
        );
        session.set_def_source_reader(std::sync::Arc::new(fixture.reader.clone()));
        assert!(
            session.settings().suggest_merge_when_clean,
            "sanity check: the setting defaults on"
        );

        let use_case = RenderMergeMod::new(fixture.reader, FakeAssetLocator::default());
        let render = use_case
            .execute(&mut session)
            .expect("rendering must succeed even with nothing to render");

        assert!(
            render.rendered.is_none(),
            "an undecided DefOverride merge must never enter the merge mod, \
             however clean its preview is"
        );
        assert!(render.entries.is_empty());
    }

    /// The other half: the very same clean, non-empty `DefOverride` merge
    /// as the test above still renders once the user decides it
    /// explicitly — only the *auto-suggested, undecided* path is narrowed,
    /// never an explicit `Action::Merge` decision.
    #[test]
    fn an_explicitly_decided_merge_on_a_clean_def_override_still_renders() {
        let fixture =
            crate::test_support::clean_override_fixture("Wall", "contributor.mod", "winner.mod");
        let mut session = crate::test_support::session_with_sources_and_mods(
            fixture.sources,
            fixture.report,
            &["core.mod", "contributor.mod", "winner.mod"],
        );
        session.set_def_source_reader(std::sync::Arc::new(fixture.reader.clone()));
        let def_key = DefKey {
            def_type: "ThingDef".to_string(),
            def_name: "Wall".to_string(),
        };
        let key = FindingKey::DefOverride {
            key: def_key.clone(),
            owners: [
                ModId::new("core.mod"),
                ModId::new("contributor.mod"),
                ModId::new("winner.mod"),
            ]
            .into_iter()
            .collect(),
        };
        decide_merge(&mut session, key.clone(), def_key);

        let use_case = RenderMergeMod::new(fixture.reader, FakeAssetLocator::default());
        let render = use_case
            .execute(&mut session)
            .expect("rendering must succeed");

        assert!(
            render.rendered.is_some(),
            "an explicit Merge decision must still render regardless"
        );
        assert_eq!(render.entries.len(), 1);
        let entry = &render.entries[0];
        assert_eq!(entry.key, key);
        assert!(matches!(entry.state, MergeState::Complete { op_count: 1 }));
        assert_eq!(entry.op_count, 1);
        assert!(
            entry.patch_file.is_some(),
            "a real op must land in a patch file"
        );
    }

    /// The third case: an undecided, auto-suggested `Merge` on a
    /// `PatchCollision` is unaffected by the `DefOverride`-only
    /// restriction above — it still enters the merge mod, since it
    /// mirrors RimWorld's own sequential patch composition rather than
    /// writing a def copy no author shipped.
    ///
    /// The preview is seeded directly (`session.cache_merge_preview`, the
    /// same technique [`a_needs_field_input_merge_is_skipped_not_rendered`]
    /// uses): a genuinely clean, `op_count > 0` *undecided* patch
    /// collision can only arise from a real, full-order patch replay
    /// (an auto-resolved
    /// field's chosen value almost always already equals what the replay
    /// produced, so op_count is usually 0), so seeding it directly is far
    /// more direct than constructing the one real fixture shape
    /// (a clobbered-map-entry restoration) that would exercise this
    /// naturally.
    #[test]
    fn an_undecided_merge_on_a_patch_collision_is_still_included() {
        let fixture = whole_def_patch_collision_fixture();
        let mut session = session_with_sources(fixture.sources, fixture.report);
        session.set_def_source_reader(std::sync::Arc::new(fixture.reader.clone()));
        assert!(session.settings().suggest_merge_when_clean);
        let def_key = DefKey {
            def_type: "ThingDef".to_string(),
            def_name: "Widget".to_string(),
        };
        let key = FindingKey::PatchCollision {
            key: def_key.clone(),
            selector: Selector::DefName,
            sub_path: None,
            mods: [ModId::new("a.mod")].into_iter().collect(),
        };
        let winner = ModId::new("core.mod");
        session.cache_merge_preview(
            MergeContext {
                slot: crate::PreviewSlot::profile(OrderSource::Current),
                choices: BTreeMap::new(),
                scope: None,
            },
            crate::MergePreview {
                key: key.clone(),
                owners: vec![ModId::new("a.mod")],
                base: ModId::new("a.mod"),
                winner: winner.clone(),
                diff: rim_merge::diff::ThreeWayDiff {
                    base: ModId::new("a.mod"),
                    fields: Vec::new(),
                },
                plan: MergePlan {
                    key: def_key,
                    selector: Selector::DefName,
                    winner,
                    owners: vec![ModId::new("a.mod")],
                    ops: vec![rim_merge::plan::PlannedOp {
                        op: rim_merge::plan::PlanOp::SetAttribute {
                            path: "techLevel".parse().unwrap(),
                            name: "dummy".to_string(),
                            value: "true".to_string(),
                        },
                        depends_on: BTreeSet::new(),
                    }],
                    unresolved: Vec::new(),
                    caveats: Vec::new(),
                },
                state: MergeState::Complete { op_count: 1 },
                structural_change: None,
                final_values: BTreeMap::new(),
            },
        );

        let use_case = RenderMergeMod::new(fixture.reader, FakeAssetLocator::default());
        let render = use_case
            .execute(&mut session)
            .expect("rendering must succeed");

        assert!(
            render.rendered.is_some(),
            "an undecided, clean PatchCollision merge must still render"
        );
        assert_eq!(render.entries.len(), 1);
        let entry = &render.entries[0];
        assert_eq!(entry.key, key);
        assert!(matches!(entry.kind, MergeEntryKind::PatchCollision));
        assert!(matches!(entry.state, MergeState::Complete { op_count: 1 }));
        assert_eq!(entry.op_count, 1);
    }

    #[test]
    fn is_zero_op_complete_matches_only_a_complete_state_with_no_ops() {
        assert!(is_zero_op_complete(&Some(MergeState::Complete {
            op_count: 0
        })));
        assert!(!is_zero_op_complete(&Some(MergeState::Complete {
            op_count: 1
        })));
        assert!(!is_zero_op_complete(&Some(MergeState::NeedsFieldInput {
            unresolved: 1,
            total: 2
        })));
        assert!(!is_zero_op_complete(&None));
    }

    /// The same clean override as above, but with the setting off: no
    /// decision exists, and `Session::redecide_clean_merge_at`'s own
    /// `suggest_merge_when_clean` check bails out before ever looking at
    /// the preview, so the ledger never auto-suggests `Merge` for it and
    /// nothing renders.
    #[test]
    fn a_clean_override_with_no_decision_is_not_rendered_when_the_setting_is_off() {
        let fixture = bionic_heart_fixture_with_conflict();
        let mut session = session_with_sources(fixture.sources, fixture.report);
        session.set_def_source_reader(std::sync::Arc::new(fixture.reader.clone()));
        let mut settings = session.settings();
        settings.suggest_merge_when_clean = false;
        session.update_settings(settings);

        let use_case = RenderMergeMod::new(fixture.reader, FakeAssetLocator::default());
        let render = use_case
            .execute(&mut session)
            .expect("rendering must succeed even with nothing to render");

        assert!(
            render.rendered.is_none(),
            "with the setting off, an undecided finding must never render"
        );
        assert!(render.entries.is_empty());
    }

    /// A finding whose preview needs a field choice (the
    /// `MergeState::NeedsFieldInput` branch) never gets an effective
    /// `Merge` action on its own — `redecide_for_clean_merge` only moves
    /// `Merge` to the front of the alternatives, it never becomes the
    /// suggestion — so it must never render just because the setting is
    /// on.
    #[test]
    fn a_conflicting_override_with_no_decision_is_never_rendered() {
        let fixture = crate::test_support::conflicting_wall_fixture();
        let mut session = crate::test_support::session_with_sources_and_mods(
            fixture.sources,
            fixture.report,
            &["core.mod", "a.mod", "b.mod"],
        );
        session.set_def_source_reader(std::sync::Arc::new(fixture.reader.clone()));
        assert!(session.settings().suggest_merge_when_clean);

        let use_case = RenderMergeMod::new(fixture.reader, FakeAssetLocator::default());
        let render = use_case
            .execute(&mut session)
            .expect("rendering must succeed even with nothing to render");

        assert!(
            render.rendered.is_none(),
            "a needs-field-input suggestion must never be treated as an effective Merge"
        );
        assert!(render.entries.is_empty());
    }

    /// [`RenderMergeMod::render`] against [`RenderTarget::Patch`] plans
    /// and renders from *that project's own* [`rim_resolve::domain::DecisionSet`]
    /// — never [`Session::decisions`] — and vice versa for
    /// [`RenderTarget::Profile`]/[`RenderMergeMod::execute`]. Both targets
    /// decide the very same finding, independently, with deliberately
    /// distinguishable choices (a real per-field choice for the profile,
    /// none at all for the patch) so the rendered `op_count` proves which
    /// decision set was actually read.
    #[test]
    fn render_reads_each_targets_own_decisions_never_the_others() {
        let fixture = bionic_heart_fixture();
        let mut session = session_with_sources(fixture.sources, fixture.report);
        let key = bionic_heart_key();
        let def_key = DefKey {
            def_type: "HediffDef".to_string(),
            def_name: "BionicHeart".to_string(),
        };

        session
            .decide(Decision {
                key: key.clone(),
                action: Action::Merge {
                    key: def_key.clone(),
                    choices: [(
                        "label".parse().unwrap(),
                        MergeChoice::From {
                            mod_id: ModId::new("ludeon.rimworld"),
                        },
                    )]
                    .into_iter()
                    .collect(),
                },
                note: None,
                decided_at: jiff::Timestamp::UNIX_EPOCH,
            })
            .expect("merge is always a valid action");

        let mut project = PatchProject::new(
            "abcdef012345".parse().expect("valid patch id"),
            "AB compat".to_string(),
            PatchModIdentity::new("test.abcompat", "AB Compat").expect("valid identity"),
            PatchScope::new([
                ModId::new("ludeon.rimworld"),
                ModId::new("example.bionicsfork"),
            ])
            .expect("two distinct members"),
            jiff::Timestamp::UNIX_EPOCH,
        );
        project
            .decide(Decision {
                key: key.clone(),
                action: Action::Merge {
                    key: def_key,
                    choices: BTreeMap::new(),
                },
                note: None,
                decided_at: jiff::Timestamp::UNIX_EPOCH,
            })
            .expect("the scope admits this finding");

        let use_case = RenderMergeMod::new(fixture.reader, FakeAssetLocator::default());

        let patch_render = use_case
            .render(&mut session, RenderTarget::Patch(&project))
            .expect("rendering the patch target must succeed");
        assert_eq!(patch_render.entries.len(), 1);
        assert_eq!(
            patch_render.entries[0].op_count, 0,
            "the patch's own (empty) choice must be what's used, not the profile's"
        );

        let profile_render = use_case
            .execute(&mut session)
            .expect("rendering the profile target must succeed");
        assert_eq!(profile_render.entries.len(), 1);
        assert_eq!(
            profile_render.entries[0].op_count, 1,
            "the profile's own decision must still render independently of the patch's"
        );
    }
}
